#include "cdealdialog.hpp"
#include "mxh/services/ITradeService.hpp"
#include <gtest/gtest.h>
using namespace mxh::ui;
namespace { struct DealInventory final : mxh::services::IInventoryService { bool present{}; const mxh::game::ItemBase* getItem(std::uint16_t) const noexcept override{return nullptr;} std::uint16_t occupiedSlotCount() const noexcept override{return 0;} std::uint16_t totalCapacity() const noexcept override{return 80;} const mxh::game::ItemBase* getWearedItem(std::uint8_t) const noexcept override{return nullptr;} bool isWearedSlotOccupied(std::uint8_t) const noexcept override{return false;} std::optional<std::uint16_t> findItemByIconIdx(std::uint16_t) const noexcept override{return present?std::optional<std::uint16_t>{0}:std::nullopt;} bool hasItem(std::uint16_t) const noexcept override{return present;} }; struct DealTradeService final : mxh::services::ITradeService { bool allow{true}; int calls{}; bool completeTrade(const std::vector<DealItem>&,const std::vector<DealItem>&,std::uint32_t) override {++calls;return allow;} }; }
TEST(DealDialog, AddsItemsAndCompletesOnce){cDealDialog d;EXPECT_TRUE(d.AddOwnItem({100,2}));EXPECT_TRUE(d.AddOtherItem({200,1}));d.SetOwnMoney(50);d.SetOtherMoney(80);bool called=false;d.SetCompleteCallback([&](const auto&a,const auto&b,std::uint32_t net){called=true;return a.size()==1&&b.size()==1&&net==30;});EXPECT_TRUE(d.Confirm());EXPECT_TRUE(called);EXPECT_TRUE(d.IsConfirmed());EXPECT_FALSE(d.AddOwnItem({300,1}));EXPECT_FALSE(d.Confirm());}
TEST(DealDialog, CallbackFailureLeavesDealUnconfirmed){cDealDialog d;d.AddOwnItem({100,1});d.SetCompleteCallback([](const auto&,const auto&,std::uint32_t){return false;});EXPECT_FALSE(d.Confirm());EXPECT_FALSE(d.IsConfirmed());EXPECT_TRUE(d.AddOtherItem({200,1}));}
TEST(DealDialog, CancelRollsBackPendingDeal){cDealDialog d;d.AddOwnItem({100,1});d.SetOwnMoney(10);d.SetOtherMoney(20);d.Cancel();EXPECT_TRUE(d.IsCancelled());EXPECT_TRUE(d.OwnItems().empty());EXPECT_TRUE(d.OtherItems().empty());EXPECT_EQ(d.NetMoney(),0u);EXPECT_FALSE(d.AddOwnItem({200,1}));}
TEST(DealDialog, ServiceBackedOwnItemRequiresInventory){cDealDialog d;DealInventory inventory;d.SetInventoryService(&inventory);EXPECT_FALSE(d.AddOwnItem({9,1}));inventory.present=true;EXPECT_TRUE(d.AddOwnItem({9,1}));}
TEST(DealDialog, TradeServiceControlsCommit){cDealDialog d;DealTradeService service;service.allow=false;d.SetTradeService(&service);ASSERT_TRUE(d.AddOwnItem({1,1}));EXPECT_FALSE(d.Confirm());EXPECT_FALSE(d.IsConfirmed());service.allow=true;EXPECT_TRUE(d.Confirm());EXPECT_EQ(service.calls,2);}
