#include "mxh/server/murimnet_runtime.hpp"
namespace mxh::server {
bool MurimNetRuntime::init(std::uint32_t maxPlayers,std::uint32_t maxRooms){release();if(!m_players.init(maxPlayers))return false;if(!m_rooms.init(maxRooms)){m_players.release();return false;}return true;}
void MurimNetRuntime::release()noexcept{m_rooms.release();m_players.release();}
MurimNetRuntimeStatus MurimNetRuntime::connect(const MurimNetPlayerInfo& info){if(info.player_id==0)return MurimNetRuntimeStatus::InvalidPlayer;if(m_players.find_player(info.player_id))return MurimNetRuntimeStatus::DuplicatePlayer;if(m_players.player_count()>=m_players.max_players())return MurimNetRuntimeStatus::CapacityFull;return m_players.add_player(info)?MurimNetRuntimeStatus::Ok:MurimNetRuntimeStatus::InvalidPlayer;}
MurimNetRuntimeStatus MurimNetRuntime::reconnect(std::uint32_t id){auto* p=m_players.find_player(id);if(!p)return MurimNetRuntimeStatus::PlayerNotFound;auto roomId=p->room_state().location_index;if(roomId==0)return MurimNetRuntimeStatus::NotInRoom;auto* room=m_rooms.get_room(roomId);if(!room)return MurimNetRuntimeStatus::RoomNotFound;if(!room->contains(id))return MurimNetRuntimeStatus::NotInRoom;p->set_connected(true);return MurimNetRuntimeStatus::Ok;}
MurimNetRuntimeStatus MurimNetRuntime::transport_disconnected(std::uint32_t id){auto* p=m_players.find_player(id);if(!p)return MurimNetRuntimeStatus::PlayerNotFound;p->set_connected(false);return MurimNetRuntimeStatus::Ok;}
MurimNetRuntimeStatus MurimNetRuntime::enter_default_room(std::uint32_t id){auto* p=m_players.find_player(id);if(!p)return MurimNetRuntimeStatus::PlayerNotFound;auto* room=m_rooms.default_room();if(!room)return MurimNetRuntimeStatus::RoomNotFound;if(room->started())return MurimNetRuntimeStatus::RoomStarted;return m_rooms.enter_room(p->room_state(),room->room_index())?MurimNetRuntimeStatus::Ok:MurimNetRuntimeStatus::CapacityFull;}
MurimNetRuntimeStatus MurimNetRuntime::disconnect(std::uint32_t id){auto* p=m_players.find_player(id);if(!p)return MurimNetRuntimeStatus::PlayerNotFound;auto roomId=p->room_state().location_index;if(roomId!=0){auto* room=m_rooms.get_room(roomId);if(!room)return MurimNetRuntimeStatus::RoomNotFound;if(room->started())return MurimNetRuntimeStatus::RoomStarted;if(!m_rooms.exit_room(p->room_state()))return MurimNetRuntimeStatus::NotInRoom;}m_players.delete_player(id);return MurimNetRuntimeStatus::Ok;}
MurimNetRuntimeStatus MurimNetRuntime::game_logout(std::uint32_t roomId,std::uint32_t id){auto* p=m_players.find_player(id);if(!p)return MurimNetRuntimeStatus::PlayerNotFound;if(p->room_state().location_index!=roomId)return MurimNetRuntimeStatus::RoomNotFound;auto* room=m_rooms.get_room(roomId);if(!room)return MurimNetRuntimeStatus::RoomNotFound;if(!room->player_out(p->room_state()))return MurimNetRuntimeStatus::NotInRoom;m_players.delete_player(id);return MurimNetRuntimeStatus::Ok;}
}

