#include "mxh/server/agent_autonote.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
TEST(AutonoteUser, NoUserDrops){AutonoteUserRequest r;r.protocol=autonote_asktoauto_syn;r.user_found=false;EXPECT_EQ(classify_autonote_user(r).kind,AutonoteUserActionKind::drop_no_user);}
TEST(AutonoteUser, AskToAutoNoPunishForwardsToMap){AutonoteUserRequest r;r.protocol=autonote_asktoauto_syn;r.user_found=true;r.user_level=user_level_gm;r.punish_remaining_seconds=0;auto a=classify_autonote_user(r);EXPECT_EQ(a.kind,AutonoteUserActionKind::forward_to_map);EXPECT_EQ(a.protocol,autonote_asktoauto_syn);}
TEST(AutonoteUser, GMAboveLevelDoesNotPunish){AutonoteUserRequest r;r.protocol=autonote_asktoauto_syn;r.user_found=true;r.user_level=user_level_gm+5;r.punish_remaining_seconds=120;auto a=classify_autonote_user(r);EXPECT_EQ(a.kind,AutonoteUserActionKind::forward_to_map);}
TEST(AutonoteUser, PunishedUserSendsPunishMessage){AutonoteUserRequest r;r.protocol=autonote_asktoauto_syn;r.user_found=true;r.user_level=0;r.punish_remaining_seconds=120;auto a=classify_autonote_user(r);EXPECT_EQ(a.kind,AutonoteUserActionKind::send_punish_to_user);EXPECT_EQ(a.protocol,autonote_punish);EXPECT_EQ(a.punish_seconds,120u);}
TEST(AutonoteUser, NonAskProtocolForwardsToMap){AutonoteUserRequest r;r.protocol=autonote_answer_syn;r.user_found=true;EXPECT_EQ(classify_autonote_user(r).kind,AutonoteUserActionKind::forward_to_map);}
TEST(AutonoteServer, AskToAutoAckPunishesAndSends){AutonoteServerRequest r;r.protocol=autonote_asktoauto_ack;r.user_object_found=true;auto a=classify_autonote_server(r);EXPECT_EQ(a.kind,AutonoteServerActionKind::asktoauto_ack_send_and_punish);EXPECT_EQ(a.punish_seconds,autonote_punish_seconds_ask);}
TEST(AutonoteServer, NotAutoUserIdMissingDrops){AutonoteServerRequest r;r.protocol=autonote_notauto;r.user_id_found=false;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::drop_no_user);}
TEST(AutonoteServer, NotAutoUseMinutes60Punishes3600Sec){AutonoteServerRequest r;r.protocol=autonote_notauto;r.user_id_found=true;r.auto_note_use_minutes=60;auto a=classify_autonote_server(r);EXPECT_EQ(a.kind,AutonoteServerActionKind::notauto_punish_and_send_to_user_if_character);EXPECT_EQ(a.punish_seconds,3600u);}
TEST(AutonoteServer, AnswerAckPunishesOther){AutonoteServerRequest r;r.protocol=autonote_answer_ack;r.auto_note_use_minutes=30;auto a=classify_autonote_server(r);EXPECT_EQ(a.kind,AutonoteServerActionKind::answer_ack_punish_other);EXPECT_EQ(a.punish_seconds,1800u);}
TEST(AutonoteServer, AnswerFailPunishCount){AutonoteServerRequest r;r.protocol=autonote_answer_fail;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::answer_fail_punish_count);}
TEST(AutonoteServer, AnswerLogoutPunishCount){AutonoteServerRequest r;r.protocol=autonote_answer_logout;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::answer_logout_punish_count);}
TEST(AutonoteServer, AnswerTimeoutFoundSends){AutonoteServerRequest r;r.protocol=autonote_answer_timeout;r.user_object_found=true;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::answer_timeout_punish_count_and_send);}
TEST(AutonoteServer, AnswerTimeoutMissingCountOnly){AutonoteServerRequest r;r.protocol=autonote_answer_timeout;r.user_object_found=false;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::answer_fail_punish_count);}
TEST(AutonoteServer, KillAutoUserIdMissingDrops){AutonoteServerRequest r;r.protocol=autonote_killauto;r.user_id_found=false;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::drop_no_user);}
TEST(AutonoteServer, KillAutoFoundSendsIfCharacter){AutonoteServerRequest r;r.protocol=autonote_killauto;r.user_id_found=true;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::killauto_send_if_character);}
TEST(AutonoteServer, DisconnectUserIdMissingDrops){AutonoteServerRequest r;r.protocol=autonote_disconnect;r.user_id_found=false;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::drop_no_user);}
TEST(AutonoteServer, DisconnectFoundSetsDisconnectFlag){AutonoteServerRequest r;r.protocol=autonote_disconnect;r.user_id_found=true;auto a=classify_autonote_server(r);EXPECT_EQ(a.kind,AutonoteServerActionKind::disconnect_if_user);EXPECT_TRUE(a.disconnect);}
TEST(AutonoteServer, DefaultForwardsIfUserFound){AutonoteServerRequest r;r.protocol=99;r.user_object_found=true;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::forward_to_user_if_found);}
TEST(AutonoteServer, DefaultDropsIfUserMissing){AutonoteServerRequest r;r.protocol=99;r.user_object_found=false;EXPECT_EQ(classify_autonote_server(r).kind,AutonoteServerActionKind::drop_no_user);}