#include "mxh/server/crypt.hpp"
#include <gtest/gtest.h>
#include <cstring>
using namespace mxh::server; using namespace mxh::crypto;
TEST(Crypt, UninitializedOperationsAreNoOpSuccess){Crypt c;char b[]="abc";EXPECT_TRUE(c.encrypt(b,3));EXPECT_STREQ(b,"abc");EXPECT_EQ(c.encrypt_crc(),0);}
TEST(Crypt, InitSwapsServerKeys){Crypt c;HselInit a,b;a.iDesCount=HSEL_DES_SINGLE;b.iDesCount=HSEL_DES_TRIPLE;c.init(a,b);EXPECT_TRUE(c.initialized());EXPECT_EQ(c.encrypt_key().iDesCount,b.iDesCount);EXPECT_EQ(c.decrypt_key().iDesCount,a.iDesCount);}
TEST(Crypt, InitializedRoundTrip){Crypt c;HselInit i;i.iDesCount=HSEL_DES_SINGLE;i.iEncryptType=HSEL_ENCRYPTTYPE_1;i.iCustomize=HSEL_KEY_TYPE_CUSTOMIZE;i.Keys.iLeftKey=1;i.Keys.iRightKey=2;i.Keys.iMiddleKey=3;i.Keys.iTotalKey=4;i.Keys.iLeftMultiGab=1;i.Keys.iRightMultiGab=1;i.Keys.iMiddleMultiGab=1;i.Keys.iTotalMultiGab=1;i.Keys.iLeftPlusGab=1;i.Keys.iRightPlusGab=1;i.Keys.iMiddlePlusGab=1;i.Keys.iTotalPlusGab=1;c.init(i,i);char b[]="hello world";char original[12];std::memcpy(original,b,12);EXPECT_TRUE(c.encrypt(b,11));EXPECT_TRUE(c.decrypt(b,11));EXPECT_EQ(std::memcmp(b,original,11),0);}
// Tests added 2026-08-03: verify Crypt::encrypt_crc() / decrypt_crc()
// return the stream CRC char (not always 0) when initialized, matching
// the legacy CCrypt::GetEnCRCConvertChar / GetDeCRCConvertChar semantics.
TEST(Crypt, EncryptCrcIsZeroWhenUninitialized){Crypt c;EXPECT_EQ(c.encrypt_crc(),0);EXPECT_EQ(c.decrypt_crc(),0);}
TEST(Crypt, EncryptCrcAfterInitBeforeDataIsZero){Crypt c;HselInit i;i.iDesCount=HSEL_DES_SINGLE;i.iEncryptType=HSEL_ENCRYPTTYPE_1;i.iCustomize=HSEL_KEY_TYPE_CUSTOMIZE;i.Keys.iLeftKey=1;i.Keys.iRightKey=2;i.Keys.iMiddleKey=3;i.Keys.iTotalKey=4;i.Keys.iLeftMultiGab=1;i.Keys.iRightMultiGab=1;i.Keys.iMiddleMultiGab=1;i.Keys.iTotalMultiGab=1;i.Keys.iLeftPlusGab=1;i.Keys.iRightPlusGab=1;i.Keys.iMiddlePlusGab=1;i.Keys.iTotalPlusGab=1;c.init(i,i);EXPECT_EQ(c.encrypt_crc(),0);EXPECT_EQ(c.decrypt_crc(),0);}
TEST(Crypt, EncryptCrcIsNonZeroAfterEncryptingData){Crypt c;HselInit i;i.iDesCount=HSEL_DES_SINGLE;i.iEncryptType=HSEL_ENCRYPTTYPE_1;i.iCustomize=HSEL_KEY_TYPE_CUSTOMIZE;i.Keys.iLeftKey=17;i.Keys.iRightKey=34;i.Keys.iMiddleKey=51;i.Keys.iTotalKey=68;i.Keys.iLeftMultiGab=1;i.Keys.iRightMultiGab=1;i.Keys.iMiddleMultiGab=1;i.Keys.iTotalMultiGab=1;i.Keys.iLeftPlusGab=1;i.Keys.iRightPlusGab=1;i.Keys.iMiddlePlusGab=1;i.Keys.iTotalPlusGab=1;c.init(i,i);char buf[8]={0};EXPECT_TRUE(c.encrypt(buf,7));EXPECT_NE(c.encrypt_crc(),0);}
TEST(Crypt, EncryptCrcIsDeterministicAfterSameDataEncrypt){Crypt c1;Crypt c2;HselInit i;i.iDesCount=HSEL_DES_SINGLE;i.iEncryptType=HSEL_ENCRYPTTYPE_1;i.iCustomize=HSEL_KEY_TYPE_CUSTOMIZE;i.Keys.iLeftKey=7;i.Keys.iRightKey=8;i.Keys.iMiddleKey=9;i.Keys.iTotalKey=10;i.Keys.iLeftMultiGab=1;i.Keys.iRightMultiGab=1;i.Keys.iMiddleMultiGab=1;i.Keys.iTotalMultiGab=1;i.Keys.iLeftPlusGab=1;i.Keys.iRightPlusGab=1;i.Keys.iMiddlePlusGab=1;i.Keys.iTotalPlusGab=1;c1.init(i,i);c2.init(i,i);char buf1[8]={0};char buf2[8]={0};c1.encrypt(buf1,7);c2.encrypt(buf2,7);EXPECT_EQ(c1.encrypt_crc(),c2.encrypt_crc());}
