#include "mxh/server/murimnet_wire_serializer.hpp"
#include "mxh/server/murimnet_channel.hpp"
#include "mxh/server/murimnet_play_room_manager.hpp"
#include "mxh/server/murimnet_player.hpp"
#include <gtest/gtest.h>
#include <cstring>
using namespace mxh::server;
static MnChannelCreateInfo mkchan(std::uint32_t idx, std::uint16_t cap, const char* title){MnChannelCreateInfo i;i.channel_index=idx;i.kind=MnChannelKind::Public;i.max_players=cap;i.title=title;return i;}
static MnPlayRoomCreateInfo mkroom(std::uint32_t idx, const char* title, std::uint8_t kind, std::uint16_t mpt, std::uint16_t mob, std::uint32_t money, std::uint16_t mapn){MnPlayRoomCreateInfo i;i.room_index=idx;i.title=title;i.kind=kind;i.max_players_per_team=mpt;i.max_observers=mob;i.money_for_play=money;i.map_num=mapn;return i;}
TEST(MurimNetWireSerializer, ChannelListSizeMatchesLegacyGetMsgLength){MurimNetChannelManager m;ASSERT_TRUE(m.init(4));ASSERT_TRUE(m.create_channel(mkchan(2,8,"PvP"))!=nullptr);ASSERT_TRUE(m.create_channel(mkchan(3,4,"Quest"))!=nullptr);auto bytes=mnh_build_channel_list_wire(m);const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+3*sizeof(MnhChannelBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, ChannelListHeaderHasCategory38AndProtocol34){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],34u);std::uint32_t obj=0;std::memcpy(&obj,bytes.data()+3,4);EXPECT_EQ(obj,0u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,1u);}
TEST(MurimNetWireSerializer, ChannelListSecondEntryIndexAndTitle){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));auto* c=m.create_channel(mkchan(5,16,"Arena"));ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),11u+2*73u);std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+11+73,4);EXPECT_EQ(idx,5u);char title[64]={0};std::memcpy(title,bytes.data()+15+73,5);EXPECT_STREQ(title,"Arena");}
TEST(MurimNetWireSerializer, ChannelListEmptyReturnsHeaderOnly){MurimNetChannelManager m;auto bytes=mnh_build_channel_list_wire(m);EXPECT_EQ(bytes.size(),11u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,0u);}
TEST(MurimNetWireSerializer, PlayRoomListSizeMatchesLegacyGetMsgLength){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(4));ASSERT_TRUE(m.create_room(mkroom(2,"Boss",0,8,2,1000,42))!=nullptr);auto bytes=mnh_build_playroom_list_wire(m);const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+2*sizeof(MnhPlayRoomBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, PlayRoomListHeaderHasCategory38AndProtocol35){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto bytes=mnh_build_playroom_list_wire(m);ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],35u);}
TEST(MurimNetWireSerializer, PlayRoomListSecondEntryFields){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto* r=m.create_room(mkroom(7,"Duel",1,5,3,500,99));ASSERT_NE(r,nullptr);auto bytes=mnh_build_playroom_list_wire(m);ASSERT_GE(bytes.size(),11u+2*82u);std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+11+82,4);EXPECT_EQ(idx,7u);char title[64]={0};std::memcpy(title,bytes.data()+15+82,4);EXPECT_STREQ(title,"Duel");EXPECT_EQ(static_cast<std::int8_t>(bytes[11+82+68]),1);}
TEST(MurimNetWireSerializer, ChannelListTitleTruncatedAtSixtyThree){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));std::string long_title(120,'X');MnChannelCreateInfo info;info.channel_index=2;info.kind=MnChannelKind::Public;info.max_players=4;info.title=long_title;auto* c=m.create_channel(info);ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),11u+2*73u);char title[64]={0};std::memcpy(title,bytes.data()+15+73,63);EXPECT_EQ(std::strlen(title),63u);for(int i=0;i<63;++i)EXPECT_EQ(title[i],'X');EXPECT_EQ(bytes[15+73+63],0);}
TEST(MurimNetWireSerializer, PlayerListSizeMatchesLegacyGetMsgLength){std::vector<MurimNetPlayer> ps(2);MurimNetPlayerInfo a;a.player_id=11;a.name="X";ps[0].init(a);MurimNetPlayerInfo b;b.player_id=22;b.name="X";ps[1].init(b);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+2*sizeof(MnhPlayerBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, PlayerListHeaderAndCount){std::vector<MurimNetPlayer> ps(1);MurimNetPlayerInfo a;a.player_id=99;a.name="X";ps[0].init(a);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerList));ASSERT_GE(bytes.size(),11u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],16u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,1u);}
TEST(MurimNetWireSerializer, PlayerListEmptyReturnsHeaderOnly){std::vector<MurimNetPlayer> ps;auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));EXPECT_EQ(bytes.size(),11u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,0u);}
TEST(MurimNetWireSerializer, PlayerListFieldMapping){MurimNetPlayer p;MurimNetPlayerInfo a;a.player_id=42;a.name="X";a.rank_point=1500;a.level=77;a.nick="X";a.play_count=10;a.win=7;a.lose=3;a.munpa="X";a.position_in_munpa=2;a.team=MnTeam::Right;p.init(a);std::vector<MurimNetPlayer> ps;ps.push_back(p);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& q:ps)if(sink)sink(q);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));ASSERT_GE(bytes.size(),11u+64u);std::uint32_t oid=0;std::memcpy(&oid,bytes.data()+11,4);EXPECT_EQ(oid,42u);std::uint16_t rp=0;std::memcpy(&rp,bytes.data()+15,2);EXPECT_EQ(rp,1500u);std::uint16_t lvl=0;std::memcpy(&lvl,bytes.data()+11+22,2);EXPECT_EQ(lvl,77u);EXPECT_EQ(static_cast<std::int8_t>(bytes[11+63]),1);EXPECT_EQ(static_cast<std::int8_t>(bytes[11+62]),2);}

TEST(MurimNetWireSerializer, ChannelInfoSizeMatchesStruct){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));auto* c=m.create_channel(mkchan(9,8,"PvP"));ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_info_wire(*c,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ChannelInfo));EXPECT_EQ(bytes.size(),sizeof(MnhMsgChannelBaseInfo));}
TEST(MurimNetWireSerializer, ChannelInfoFieldMapping){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));MnChannelCreateInfo info;info.channel_index=42;info.kind=MnChannelKind::Private;info.max_players=123;info.title="Arena";auto* c=m.create_channel(info);ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_info_wire(*c,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ChannelInfo));ASSERT_GE(bytes.size(),sizeof(MnhMsgChannelBaseInfo));std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+7,4);EXPECT_EQ(idx,42u);char title[64]={0};std::memcpy(title,bytes.data()+11,5);EXPECT_STREQ(title,"Arena");std::int8_t kind=0;std::memcpy(&kind,bytes.data()+75,1);EXPECT_EQ(kind,static_cast<std::int8_t>(MnChannelKind::Private));std::uint16_t mp=0;std::memcpy(&mp,bytes.data()+76,2);EXPECT_EQ(mp,123u);}
TEST(MurimNetWireSerializer, PlayRoomInfoSizeMatchesStruct){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto* r=m.create_room(mkroom(5,"Boss",0,8,2,1000,42));ASSERT_NE(r,nullptr);auto bytes=mnh_build_playroom_info_wire(*r,static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayRoomInfo));EXPECT_EQ(bytes.size(),sizeof(MnhMsgPlayRoomBaseInfo));}
TEST(MurimNetWireSerializer, PlayRoomInfoFieldMapping){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto* r=m.create_room(mkroom(7,"Duel",2,5,3,500,99));ASSERT_NE(r,nullptr);r->play_start(true);auto bytes=mnh_build_playroom_info_wire(*r,static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayRoomInfo));ASSERT_GE(bytes.size(),sizeof(MnhMsgPlayRoomBaseInfo));std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+7,4);EXPECT_EQ(idx,7u);char title[64]={0};std::memcpy(title,bytes.data()+11,4);EXPECT_STREQ(title,"Duel");std::int8_t kind=0;std::memcpy(&kind,bytes.data()+75,1);EXPECT_EQ(kind,2);std::uint16_t mo=0;std::memcpy(&mo,bytes.data()+76,2);EXPECT_EQ(mo,3u);std::uint16_t mpt=0;std::memcpy(&mpt,bytes.data()+78,2);EXPECT_EQ(mpt,5u);std::uint32_t money=0;std::memcpy(&money,bytes.data()+80,4);EXPECT_EQ(money,500u);std::uint8_t started=0;std::memcpy(&started,bytes.data()+86,1);EXPECT_EQ(started,1u);std::uint16_t mapn=0;std::memcpy(&mapn,bytes.data()+87,2);EXPECT_EQ(mapn,99u);}
TEST(MurimNetWireSerializer, PlayerInfoSizeMatchesStruct){MurimNetPlayer p;MurimNetPlayerInfo a;a.player_id=42;a.name="X";p.init(a);auto bytes=mnh_build_player_info_wire(p,static_cast<std::uint8_t>(MurimNetProtocol::Player_Info_Ack));EXPECT_EQ(bytes.size(),sizeof(MnhMsgPlayerBaseInfo));}
TEST(MurimNetWireSerializer, PlayerInfoFieldMapping){MurimNetPlayer p;MurimNetPlayerInfo a;a.player_id=42;a.name="Hero";a.rank_point=1500;a.level=77;a.nick="N";a.play_count=10;a.win=7;a.lose=3;a.munpa="M";a.position_in_munpa=2;a.team=MnTeam::Right;p.init(a);auto bytes=mnh_build_player_info_wire(p,static_cast<std::uint8_t>(MurimNetProtocol::Player_Info_Ack));ASSERT_GE(bytes.size(),sizeof(MnhMsgPlayerBaseInfo));std::uint32_t oid=0;std::memcpy(&oid,bytes.data()+7,4);EXPECT_EQ(oid,42u);std::uint16_t rp=0;std::memcpy(&rp,bytes.data()+11,2);EXPECT_EQ(rp,1500u);char name[17]={0};std::memcpy(name,bytes.data()+13,4);EXPECT_STREQ(name,"Hero");std::uint16_t lvl=0;std::memcpy(&lvl,bytes.data()+29,2);EXPECT_EQ(lvl,77u);std::uint8_t team=0;std::memcpy(&team,bytes.data()+70,1);EXPECT_EQ(team,static_cast<std::uint8_t>(MnTeam::Right));}
TEST(MurimNetWireSerializer, ChatWireBasicSizeAndFields){std::string text="hello";auto bytes=mnh_build_chat_wire(7u,text,static_cast<std::uint8_t>(MurimNetProtocol::Chat_All));ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],MNH_CATEGORY_MURIMNET);std::uint8_t proto=0;std::memcpy(&proto,bytes.data()+2,1);EXPECT_EQ(proto,static_cast<std::uint8_t>(MurimNetProtocol::Chat_All));std::uint32_t sid=0;std::memcpy(&sid,bytes.data()+3,4);EXPECT_EQ(sid,7u);EXPECT_EQ(bytes.size(),7u+5u+1u);char body[6]={0};std::memcpy(body,bytes.data()+7,5);EXPECT_STREQ(body,"hello");EXPECT_EQ(bytes[bytes.size()-1],0);}
TEST(MurimNetWireSerializer, ChatWireEmptyTextIsEightBytes){auto bytes=mnh_build_chat_wire(1u,"",static_cast<std::uint8_t>(MurimNetProtocol::Chat_All));EXPECT_EQ(bytes.size(),8u);EXPECT_EQ(bytes[7],0);}
TEST(MurimNetWireSerializer, ChatWireTrimsAtMaxLengthAndTerminates){std::string text(200,'A');auto bytes=mnh_build_chat_wire(99u,text,static_cast<std::uint8_t>(MurimNetProtocol::Chat_All));EXPECT_EQ(bytes.size(),7u+MNH_MAX_CHAT_LENGTH+1u);for(std::size_t i=0;i<MNH_MAX_CHAT_LENGTH;++i)EXPECT_EQ(bytes[7+i],'A');EXPECT_EQ(bytes[bytes.size()-1],0);}
TEST(MurimNetWireSerializer, TeamChangeSizeIsThirteenBytes){auto bytes=mnh_build_team_change_wire(0u,0u,0,0,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Ack));EXPECT_EQ(bytes.size(),sizeof(MnhMsgTeamChange));EXPECT_EQ(bytes.size(),13u);}
TEST(MurimNetWireSerializer, TeamChangeHeaderHasCategoryAndProtocol){auto bytes=mnh_build_team_change_wire(0u,0u,0,0,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Ack));ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],MNH_CATEGORY_MURIMNET);std::uint8_t proto=0;std::memcpy(&proto,bytes.data()+2,1);EXPECT_EQ(proto,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Ack));std::uint32_t sid=0;std::memcpy(&sid,bytes.data()+3,4);EXPECT_EQ(sid,0u);}
TEST(MurimNetWireSerializer, TeamChangeFieldMapping){auto bytes=mnh_build_team_change_wire(55u,42u,1,2,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Ack));ASSERT_EQ(bytes.size(),13u);std::uint32_t mover=0;std::memcpy(&mover,bytes.data()+7,4);EXPECT_EQ(mover,42u);std::uint8_t from=0;std::memcpy(&from,bytes.data()+11,1);EXPECT_EQ(from,1u);std::uint8_t to=0;std::memcpy(&to,bytes.data()+12,1);EXPECT_EQ(to,2u);}
TEST(MurimNetWireSerializer, TeamChangeNackSameShape){auto bytes=mnh_build_team_change_wire(0u,99u,0,1,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Nack));ASSERT_EQ(bytes.size(),13u);std::uint8_t proto=0;std::memcpy(&proto,bytes.data()+2,1);EXPECT_EQ(proto,static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Nack));std::uint32_t mover=0;std::memcpy(&mover,bytes.data()+7,4);EXPECT_EQ(mover,99u);}
TEST(MurimNetWireSerializer, ShortWireByteSizeIsEight){auto bytes=mnh_build_byte_wire(0u,7,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),8u);EXPECT_EQ(bytes[7],7u);}
TEST(MurimNetWireSerializer, ShortWireWordSizeIsNine){auto bytes=mnh_build_word_wire(0u,0xCAFEu,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),9u);std::uint16_t v=0;std::memcpy(&v,bytes.data()+7,2);EXPECT_EQ(v,0xCAFEu);}
TEST(MurimNetWireSerializer, ShortWireWord2SizeIsEleven){auto bytes=mnh_build_word2_wire(0u,0x1111u,0x2222u,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),11u);std::uint16_t v1=0;std::memcpy(&v1,bytes.data()+7,2);EXPECT_EQ(v1,0x1111u);std::uint16_t v2=0;std::memcpy(&v2,bytes.data()+9,2);EXPECT_EQ(v2,0x2222u);}
TEST(MurimNetWireSerializer, ShortWireDwordSizeIsEleven){auto bytes=mnh_build_dword_wire(0u,0xDEADBEEFu,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),11u);std::uint32_t v=0;std::memcpy(&v,bytes.data()+7,4);EXPECT_EQ(v,0xDEADBEEFu);}
TEST(MurimNetWireSerializer, ShortWireDword2SizeIsFifteen){auto bytes=mnh_build_dword2_wire(0u,0x11111111u,0x22222222u,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),15u);std::uint32_t v1=0;std::memcpy(&v1,bytes.data()+7,4);EXPECT_EQ(v1,0x11111111u);std::uint32_t v2=0;std::memcpy(&v2,bytes.data()+11,4);EXPECT_EQ(v2,0x22222222u);}
TEST(MurimNetWireSerializer, ShortWireDword3SizeIsNineteen){auto bytes=mnh_build_dword3_wire(0u,0x01010101u,0x02020202u,0x03030303u,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),19u);std::uint32_t v1=0;std::memcpy(&v1,bytes.data()+7,4);EXPECT_EQ(v1,0x01010101u);std::uint32_t v2=0;std::memcpy(&v2,bytes.data()+11,4);EXPECT_EQ(v2,0x02020202u);std::uint32_t v3=0;std::memcpy(&v3,bytes.data()+15,4);EXPECT_EQ(v3,0x03030303u);}
TEST(MurimNetWireSerializer, ShortWireDword4SizeIsTwentyThree){auto bytes=mnh_build_dword4_wire(0u,0x01010101u,0x02020202u,0x03030303u,0x04040404u,static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange));ASSERT_EQ(bytes.size(),23u);std::uint32_t v4=0;std::memcpy(&v4,bytes.data()+19,4);EXPECT_EQ(v4,0x04040404u);}
