#include "mxh/server/murimnet_runtime.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
static MurimNetPlayerInfo info(std::uint32_t id){MurimNetPlayerInfo i;i.player_id=id;i.agent_num=2;i.unique_id_in_agent=3;i.back_map_num=4;return i;}
TEST(MurimNetRuntime, ConnectEnterReconnectDisconnectFlow){MurimNetRuntime r;ASSERT_TRUE(r.init(4,2));EXPECT_EQ(r.connect(info(10)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_room(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.disconnect(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(10),nullptr);}
TEST(MurimNetRuntime, ConnectRejectsInvalidDuplicateAndCapacity){MurimNetRuntime r;ASSERT_TRUE(r.init(1,1));EXPECT_EQ(r.connect(info(0)),MurimNetRuntimeStatus::InvalidPlayer);EXPECT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::DuplicatePlayer);EXPECT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::CapacityFull);}
TEST(MurimNetRuntime, ReconnectRequiresValidRoomMembership){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::NotInRoom);EXPECT_EQ(r.reconnect(2),MurimNetRuntimeStatus::PlayerNotFound);}
TEST(MurimNetRuntime, StartedRoomDefersNormalDisconnect){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);EXPECT_EQ(r.disconnect(1),MurimNetRuntimeStatus::RoomStarted);EXPECT_NE(r.players().find_player(1),nullptr);}
TEST(MurimNetRuntime, GameLogoutRemovesStartedPlayer){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);EXPECT_EQ(r.game_logout(1,1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1),nullptr);}
TEST(MurimNetRuntime, ReleaseClearsManagers){MurimNetRuntime r;ASSERT_TRUE(r.init(2,2));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);r.release();EXPECT_EQ(r.players().player_count(),0u);EXPECT_EQ(r.rooms().room_count(),0u);}

TEST(MurimNetRuntime, TransportDisconnectKeepsStartedPlayerForReconnect){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);ASSERT_EQ(r.transport_disconnected(1),MurimNetRuntimeStatus::Ok);auto* p=r.players().find_player(1);ASSERT_NE(p,nullptr);EXPECT_FALSE(p->connected());EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::Ok);EXPECT_TRUE(p->connected());}
TEST(MurimNetRuntime, RemovedPlayerCannotReconnectOrDisconnectTransport){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.disconnect(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::PlayerNotFound);EXPECT_EQ(r.transport_disconnected(1),MurimNetRuntimeStatus::PlayerNotFound);}

TEST(MurimNetRuntime, OnlyCaptainCanRequestStart){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(2),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.request_start(2),MurimNetRuntimeStatus::NotCaptain);EXPECT_EQ(r.request_start(1),MurimNetRuntimeStatus::Ok);}
TEST(MurimNetRuntime, StartAckMovesAllPlayersToGame){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(2),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.start_ack(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location,MnPlayerLocation::Game);EXPECT_EQ(r.players().find_player(2)->room_state().location,MnPlayerLocation::Game);EXPECT_EQ(r.start_ack(1),MurimNetRuntimeStatus::AlreadyStarted);}
TEST(MurimNetRuntime, StartNackMovesPlayersToResult){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.start_nack(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location,MnPlayerLocation::Result);EXPECT_FALSE(r.rooms().default_room()->started());}

TEST(MurimNetRuntime, DefaultChannelFlow){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location_index,1u);EXPECT_EQ(r.exit_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);}
TEST(MurimNetRuntime, ChannelCapacityIsReported){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(3)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_channel(2),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_channel(3),MurimNetRuntimeStatus::Ok);}
TEST(MurimNetRuntime, EnterDefaultChannelSetsChannelLocation){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location,MnPlayerLocation::Channel);EXPECT_EQ(r.exit_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location,MnPlayerLocation::None);}
TEST(MurimNetRuntime, EnterDefaultRoomSetsPlayRoomLocation){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().location,MnPlayerLocation::PlayRoom);}
TEST(MurimNetRuntime, SelectChannelModeAcceptsIdChannelAndPlayRoom){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::Id),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::Channel),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::PlayRoom),MurimNetRuntimeStatus::Ok);}
TEST(MurimNetRuntime, SelectChannelModeRejectsMaxAndAbove){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::Max),MurimNetRuntimeStatus::InvalidChannelMode);EXPECT_EQ(r.select_channel_mode(1,static_cast<MnChannelMode>(99)),MurimNetRuntimeStatus::InvalidChannelMode);}
TEST(MurimNetRuntime, SelectChannelModeRequiresChannelMembership){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::Id),MurimNetRuntimeStatus::NotInRoom);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.select_channel_mode(1,MnChannelMode::Id),MurimNetRuntimeStatus::NotInRoom);}
TEST(MurimNetRuntime, SelectChannelModeRequiresKnownPlayer){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));EXPECT_EQ(r.select_channel_mode(99,MnChannelMode::Id),MurimNetRuntimeStatus::PlayerNotFound);}
TEST(MurimNetRuntime, TeamChangeMovesPlayerBetweenTeams){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(2),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.team_change(1,MnTeam::Right),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().team,MnTeam::Right);EXPECT_EQ(r.rooms().default_room()->team_count(MnTeam::Left),0u);EXPECT_EQ(r.rooms().default_room()->team_count(MnTeam::Right),2u);}
TEST(MurimNetRuntime, TeamChangeSameTeamReturnsCapacityFull){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.team_change(1,MnTeam::Left),MurimNetRuntimeStatus::CapacityFull);EXPECT_EQ(r.players().find_player(1)->room_state().team,MnTeam::Left);}
TEST(MurimNetRuntime, TeamChangeRequiresKnownPlayer){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));EXPECT_EQ(r.team_change(99,MnTeam::Left),MurimNetRuntimeStatus::PlayerNotFound);}
TEST(MurimNetRuntime, TeamChangeRequiresRoomMembership){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.team_change(1,MnTeam::Right),MurimNetRuntimeStatus::NotInRoom);ASSERT_EQ(r.enter_default_channel(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.team_change(1,MnTeam::Right),MurimNetRuntimeStatus::NotInRoom);}
TEST(MurimNetRuntime, TeamChangeRejectedAfterRoomStarted){MurimNetRuntime r;ASSERT_TRUE(r.init(3,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);EXPECT_EQ(r.team_change(1,MnTeam::Right),MurimNetRuntimeStatus::RoomStarted);EXPECT_EQ(r.players().find_player(1)->room_state().team,MnTeam::Left);}
TEST(MurimNetRuntime, TeamChangeRejectsObserverOverflow){MurimNetRuntime r;ASSERT_TRUE(r.init(3,2));MnPlayRoomCreateInfo custom;custom.title="obs";custom.max_players_per_team=2;custom.max_observers=1;auto* room=r.rooms().create_room(custom);ASSERT_NE(room,nullptr);ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::Ok);ASSERT_TRUE(r.rooms().enter_room(r.players().find_player(1)->room_state(),room->room_index()));ASSERT_TRUE(r.rooms().enter_room(r.players().find_player(2)->room_state(),room->room_index()));EXPECT_EQ(r.team_change(1,MnTeam::Observer),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1)->room_state().team,MnTeam::Observer);EXPECT_EQ(r.team_change(2,MnTeam::Observer),MurimNetRuntimeStatus::CapacityFull);}
