#include "mxh/server/murimnet_runtime.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
static MurimNetPlayerInfo info(std::uint32_t id){MurimNetPlayerInfo i;i.player_id=id;i.agent_num=2;i.unique_id_in_agent=3;i.back_map_num=4;return i;}
TEST(MurimNetRuntime, ConnectEnterReconnectDisconnectFlow){MurimNetRuntime r;ASSERT_TRUE(r.init(4,2));EXPECT_EQ(r.connect(info(10)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.enter_default_room(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.disconnect(10),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(10),nullptr);}
TEST(MurimNetRuntime, ConnectRejectsInvalidDuplicateAndCapacity){MurimNetRuntime r;ASSERT_TRUE(r.init(1,1));EXPECT_EQ(r.connect(info(0)),MurimNetRuntimeStatus::InvalidPlayer);EXPECT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::DuplicatePlayer);EXPECT_EQ(r.connect(info(2)),MurimNetRuntimeStatus::CapacityFull);}
TEST(MurimNetRuntime, ReconnectRequiresValidRoomMembership){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::NotInRoom);EXPECT_EQ(r.reconnect(2),MurimNetRuntimeStatus::PlayerNotFound);}
TEST(MurimNetRuntime, StartedRoomDefersNormalDisconnect){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);EXPECT_EQ(r.disconnect(1),MurimNetRuntimeStatus::RoomStarted);EXPECT_NE(r.players().find_player(1),nullptr);}
TEST(MurimNetRuntime, GameLogoutRemovesStartedPlayer){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);EXPECT_EQ(r.game_logout(1,1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.players().find_player(1),nullptr);}
TEST(MurimNetRuntime, ReleaseClearsManagers){MurimNetRuntime r;ASSERT_TRUE(r.init(2,2));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);r.release();EXPECT_EQ(r.players().player_count(),0u);EXPECT_EQ(r.rooms().room_count(),0u);}

TEST(MurimNetRuntime, TransportDisconnectKeepsStartedPlayerForReconnect){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.enter_default_room(1),MurimNetRuntimeStatus::Ok);r.rooms().default_room()->play_start(true);ASSERT_EQ(r.transport_disconnected(1),MurimNetRuntimeStatus::Ok);auto* p=r.players().find_player(1);ASSERT_NE(p,nullptr);EXPECT_FALSE(p->connected());EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::Ok);EXPECT_TRUE(p->connected());}
TEST(MurimNetRuntime, RemovedPlayerCannotReconnectOrDisconnectTransport){MurimNetRuntime r;ASSERT_TRUE(r.init(2,1));ASSERT_EQ(r.connect(info(1)),MurimNetRuntimeStatus::Ok);ASSERT_EQ(r.disconnect(1),MurimNetRuntimeStatus::Ok);EXPECT_EQ(r.reconnect(1),MurimNetRuntimeStatus::PlayerNotFound);EXPECT_EQ(r.transport_disconnected(1),MurimNetRuntimeStatus::PlayerNotFound);}
