#include "mxh/server/murimnet_protocol.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
TEST(MurimNetProtocol, ChangeToMurimNetValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ChangetoMurimNet_Syn),0);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ChangetoMurimNet_Ack),1);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ChangetoMurimNet_Nack),2);}
TEST(MurimNetProtocol, ReturnToMurimNetValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ReturntoMurimNet_Syn),3);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ReturntoMurimNet_Ack),4);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::ReturntoMurimNet_Nack),5);}
TEST(MurimNetProtocol, ConnectValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Connect_Syn),6);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Connect_Ack),7);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Connect_Nack),8);}
TEST(MurimNetProtocol, ReconnectValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Reconnect_Syn),9);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Reconnect_Ack),10);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Reconnect_Nack),11);}
TEST(MurimNetProtocol, DisconnectValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Disconnect_Syn),12);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Disconnect_Ack),13);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Disconnect_Nack),14);}
TEST(MurimNetProtocol, PlayRoomBaseValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayRoomInfo),15);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerList),16);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerIn),17);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerOut),18);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_Captain),19);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerRein),20);}
TEST(MurimNetProtocol, TeamChangeAndStartValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Syn),21);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Ack),22);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_TeamChange_Nack),23);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_Start),24);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_Start_Syn),25);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_Start_Ack),26);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Pr_Start_Nack),27);}
TEST(MurimNetProtocol, ChannelBaseValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ChannelInfo),28);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerIn),29);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerOut),30);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_Captain),31);}
TEST(MurimNetProtocol, ChannelListValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ModeChange),32);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList),33);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_ChannelInfoList),34);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayRoomInfoList),35);}
TEST(MurimNetProtocol, ChannelActionValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinPlayRoom_Syn),36);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinPlayRoom_Ack),37);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinPlayRoom_Nack),38);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreatePlayRoom_Syn),39);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreatePlayRoom_Ack),40);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreatePlayRoom_Nack),41);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinChannel_Syn),42);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinChannel_Ack),43);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_JoinChannel_Nack),44);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreateChannel_Syn),45);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreateChannel_Ack),46);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chnl_CreateChannel_Nack),47);}
TEST(MurimNetProtocol, ChatAndServerInfoValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Chat_All),48);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::MurimServerIn_Syn),49);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::MurimServerIn_Ack),50);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::MurimServerIn_Nack),51);}
TEST(MurimNetProtocol, ToMurimServerValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::PlayRoom_Info_Syn),52);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::PlayRoom_Info_Ack),53);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::PlayRoom_Info_Nack),54);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Player_Info_Syn),55);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Player_Info_Ack),56);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::Player_Info_Nack),57);}
TEST(MurimNetProtocol, NotifyValues){EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::NotifyToMn_PlayerLogout),58);EXPECT_EQ(static_cast<std::uint8_t>(MurimNetProtocol::NotifyToMn_GameEnd),59);}
TEST(MurimNetProtocol, LowercaseAliasesMatchLegacy){EXPECT_EQ(murimnet_changetomurimnet_syn,0);EXPECT_EQ(murimnet_connect_syn,6);EXPECT_EQ(murimnet_reconnect_syn,9);EXPECT_EQ(murimnet_disconnect_ack,13);EXPECT_EQ(murimnet_pr_teamchange_syn,21);EXPECT_EQ(murimnet_chnl_modechange,32);EXPECT_EQ(murimnet_chat_all,48);EXPECT_EQ(murimnet_notifytomn_player_logout,58);EXPECT_EQ(murimnet_notifytomn_gameend,59);}
