#include "mxh/server/murimnet_wire_serializer.hpp"
#include "mxh/server/murimnet_channel.hpp"
#include "mxh/server/murimnet_play_room_manager.hpp"
#include "mxh/server/murimnet_player.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
static MnChannelCreateInfo mkchan(std::uint32_t idx, std::uint16_t cap, const char* title){MnChannelCreateInfo i;i.channel_index=idx;i.kind=MnChannelKind::Public;i.max_players=cap;i.title=title;return i;}
static MnPlayRoomCreateInfo mkroom(std::uint32_t idx, const char* title, std::uint8_t kind, std::uint16_t mpt, std::uint16_t mob, std::uint32_t money, std::uint16_t mapn){MnPlayRoomCreateInfo i;i.room_index=idx;i.title=title;i.kind=kind;i.max_players_per_team=mpt;i.max_observers=mob;i.money_for_play=money;i.map_num=mapn;return i;}
TEST(MurimNetWireSerializer, ChannelListSizeMatchesLegacyGetMsgLength){MurimNetChannelManager m;ASSERT_TRUE(m.init(4));ASSERT_TRUE(m.create_channel(mkchan(2,8,"PvP"))!=nullptr);ASSERT_TRUE(m.create_channel(mkchan(3,4,"Quest"))!=nullptr);auto bytes=mnh_build_channel_list_wire(m);const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+3*sizeof(MnhChannelBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, ChannelListHeaderHasCategory38AndProtocol34){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],34u);std::uint32_t obj=0;std::memcpy(&obj,bytes.data()+3,4);EXPECT_EQ(obj,0u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,1u);}
TEST(MurimNetWireSerializer, ChannelListSecondEntryIndexAndTitle){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));auto* c=m.create_channel(mkchan(5,16,"Arena"));ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),11u+2*73u);std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+11+73,4);EXPECT_EQ(idx,5u);char title[64]={0};std::memcpy(title,bytes.data()+15+73,5);EXPECT_STREQ(title,"Arena");}
TEST(MurimNetWireSerializer, ChannelListEmptyReturnsHeaderOnly){MurimNetChannelManager m;auto bytes=mnh_build_channel_list_wire(m);EXPECT_EQ(bytes.size(),11u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,0u);}
TEST(MurimNetWireSerializer, PlayRoomListSizeMatchesLegacyGetMsgLength){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(4));ASSERT_TRUE(m.create_room(mkroom(2,"Boss",0,8,2,1000,42))!=nullptr);auto bytes=mnh_build_playroom_list_wire(m);const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+2*sizeof(MnhPlayRoomBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, PlayRoomListHeaderHasCategory38AndProtocol35){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto bytes=mnh_build_playroom_list_wire(m);ASSERT_GE(bytes.size(),7u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],35u);}
TEST(MurimNetWireSerializer, PlayRoomListSecondEntryFields){MurimNetPlayRoomManager m;ASSERT_TRUE(m.init(2));auto* r=m.create_room(mkroom(7,"Duel",1,5,3,500,99));ASSERT_NE(r,nullptr);auto bytes=mnh_build_playroom_list_wire(m);ASSERT_GE(bytes.size(),11u+2*82u);std::uint32_t idx=0;std::memcpy(&idx,bytes.data()+11+82,4);EXPECT_EQ(idx,7u);char title[64]={0};std::memcpy(title,bytes.data()+15+82,4);EXPECT_STREQ(title,"Duel");EXPECT_EQ(static_cast<std::int8_t>(bytes[11+82+68]),1);}
TEST(MurimNetWireSerializer, ChannelListTitleTruncatedAtSixtyThree){MurimNetChannelManager m;ASSERT_TRUE(m.init(2));std::string long_title(120,'X');MnChannelCreateInfo info;info.channel_index=2;info.kind=MnChannelKind::Public;info.max_players=4;info.title=long_title;auto* c=m.create_channel(info);ASSERT_NE(c,nullptr);auto bytes=mnh_build_channel_list_wire(m);ASSERT_GE(bytes.size(),11u+2*73u);char title[64]={0};std::memcpy(title,bytes.data()+15+73,63);EXPECT_EQ(std::strlen(title),63u);for(int i=0;i<63;++i)EXPECT_EQ(title[i],'X');EXPECT_EQ(bytes[15+73+63],0);}
#include <cstring>

TEST(MurimNetWireSerializer, PlayerListSizeMatchesLegacyGetMsgLength){std::vector<MurimNetPlayer> ps(2);MurimNetPlayerInfo a;a.player_id=11;a.name="X";ps[0].init(a);MurimNetPlayerInfo b;b.player_id=22;b.name="X";ps[1].init(b);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));const std::size_t expected=sizeof(MnhWireBase)+sizeof(std::uint32_t)+2*sizeof(MnhPlayerBaseInfo);EXPECT_EQ(bytes.size(),expected);}
TEST(MurimNetWireSerializer, PlayerListHeaderAndCount){std::vector<MurimNetPlayer> ps(1);MurimNetPlayerInfo a;a.player_id=99;a.name="X";ps[0].init(a);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Pr_PlayerList));ASSERT_GE(bytes.size(),11u);EXPECT_EQ(bytes[1],38u);EXPECT_EQ(bytes[2],16u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,1u);}
TEST(MurimNetWireSerializer, PlayerListEmptyReturnsHeaderOnly){std::vector<MurimNetPlayer> ps;auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& p:ps)if(sink)sink(p);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));EXPECT_EQ(bytes.size(),11u);std::uint32_t total=0;std::memcpy(&total,bytes.data()+7,4);EXPECT_EQ(total,0u);}
TEST(MurimNetWireSerializer, PlayerListFieldMapping){MurimNetPlayer p;MurimNetPlayerInfo a;a.player_id=42;a.name="X";a.rank_point=1500;a.level=77;a.nick="X";a.play_count=10;a.win=7;a.lose=3;a.munpa="X";a.position_in_munpa=2;a.team=MnTeam::Right;p.init(a);std::vector<MurimNetPlayer> ps;ps.push_back(p);auto bytes=mnh_build_player_list_wire([&](const std::function<void(const MurimNetPlayer&)>& sink){for(const auto& q:ps)if(sink)sink(q);},static_cast<std::uint8_t>(MurimNetProtocol::Chnl_PlayerList));ASSERT_GE(bytes.size(),11u+64u);std::uint32_t oid=0;std::memcpy(&oid,bytes.data()+11,4);EXPECT_EQ(oid,42u);std::uint16_t rp=0;std::memcpy(&rp,bytes.data()+15,2);EXPECT_EQ(rp,1500u);std::uint16_t lvl=0;std::memcpy(&lvl,bytes.data()+11+22,2);EXPECT_EQ(lvl,77u);EXPECT_EQ(static_cast<std::int8_t>(bytes[11+63]),1);EXPECT_EQ(static_cast<std::int8_t>(bytes[11+62]),2);}