#include "mxh/server/murimnet_play_room.hpp"
#include <gtest/gtest.h>
using namespace mxh::server;
static MnPlayRoomCreateInfo info(){MnPlayRoomCreateInfo i;i.room_index=7;i.title="room";i.max_players_per_team=2;i.max_observers=1;i.map_num=12;return i;}
TEST(MurimNetPlayRoom, CreateAndBalancedJoin){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1},b{2},c{3};ASSERT_TRUE(r.player_in(a));ASSERT_TRUE(r.player_in(b));ASSERT_TRUE(r.player_in(c));EXPECT_TRUE(a.captain);EXPECT_EQ(a.team,MnTeam::Left);EXPECT_EQ(b.team,MnTeam::Right);EXPECT_EQ(c.team,MnTeam::Left);EXPECT_EQ(r.player_count(),3u);}
TEST(MurimNetPlayRoom, CapacityAndDuplicateAreRejected){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1},b{2},c{3},d{4},e{5};EXPECT_TRUE(r.player_in(a));EXPECT_FALSE(r.player_in(a));EXPECT_TRUE(r.player_in(b));EXPECT_TRUE(r.player_in(c));EXPECT_TRUE(r.player_in(d));EXPECT_FALSE(r.player_in(e));}
TEST(MurimNetPlayRoom, CaptainTransfersOnLeave){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1},b{2};ASSERT_TRUE(r.player_in(a));ASSERT_TRUE(r.player_in(b));ASSERT_TRUE(r.player_out(a));EXPECT_TRUE(b.captain);EXPECT_EQ(a.location,MnPlayerLocation::None);}
TEST(MurimNetPlayRoom, TeamChangeHonorsObserverLimit){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1},b{2};ASSERT_TRUE(r.player_in(a));ASSERT_TRUE(r.player_in(b));EXPECT_TRUE(r.team_change(a,MnTeam::Left,MnTeam::Observer));EXPECT_EQ(a.team,MnTeam::Observer);EXPECT_FALSE(r.team_change(b,MnTeam::Right,MnTeam::Observer));}
TEST(MurimNetPlayRoom, PlayStartUpdatesPlayerLocations){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1},b{2};ASSERT_TRUE(r.player_in(a));ASSERT_TRUE(r.player_in(b));r.play_start(true);EXPECT_TRUE(r.started());EXPECT_EQ(a.location,MnPlayerLocation::Game);MnRoomPlayer late{3};EXPECT_FALSE(r.player_in(late));r.play_start(false);EXPECT_EQ(a.location,MnPlayerLocation::Result);EXPECT_EQ(b.location,MnPlayerLocation::Result);}
TEST(MurimNetPlayRoom, ReleaseClearsPlayersAndLocation){MurimNetPlayRoom r;ASSERT_TRUE(r.create(info()));MnRoomPlayer a{1};ASSERT_TRUE(r.player_in(a));r.release();EXPECT_EQ(r.player_count(),0u);EXPECT_EQ(a.location,MnPlayerLocation::None);EXPECT_FALSE(a.captain);}
