#include "mxh/server/murimnet_wire.hpp"
#include "mxh/server/murimnet_protocol.hpp"
#include <gtest/gtest.h>
#include <cstddef>
using namespace mxh::server;
TEST(MurimNetWire, HeaderSizesAreThreeAndSeven){EXPECT_EQ(sizeof(MnhWireRoot),3u);EXPECT_EQ(sizeof(MnhWireBase),7u);}
TEST(MurimNetWire, ShortPayloadSizesMatchLegacy){EXPECT_EQ(sizeof(MnhWireByte),8u);EXPECT_EQ(sizeof(MnhWireDword),11u);EXPECT_EQ(sizeof(MnhWireDword2),15u);EXPECT_EQ(sizeof(MnhWireDword3),19u);EXPECT_EQ(sizeof(MnhWireDword4),23u);EXPECT_EQ(sizeof(MnhWireWord),9u);EXPECT_EQ(sizeof(MnhWireWord2),11u);}
TEST(MurimNetWire, PlayerBaseInfoIsSixtyFourBytes){EXPECT_EQ(sizeof(MnhPlayerBaseInfo),64u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,dwObjectID),0u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,wRankPoint),4u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,strPlayerName),6u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,Level),22u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,strNick),24u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,wPlayCount),40u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,wWin),42u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,wLose),44u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,strMunpa),46u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,cbPositionInMunpa),62u);EXPECT_EQ(offsetof(MnhPlayerBaseInfo,cbTeam),63u);}
TEST(MurimNetWire, ChannelBaseInfoIsSeventyThreeBytes){EXPECT_EQ(sizeof(MnhChannelBaseInfo),73u);EXPECT_EQ(offsetof(MnhChannelBaseInfo,dwChannelIndex),0u);EXPECT_EQ(offsetof(MnhChannelBaseInfo,strChannelTitle),4u);EXPECT_EQ(offsetof(MnhChannelBaseInfo,cbChannelKind),68u);EXPECT_EQ(offsetof(MnhChannelBaseInfo,wMaxPlayer),69u);EXPECT_EQ(offsetof(MnhChannelBaseInfo,wPlayerNum),71u);}
TEST(MurimNetWire, PlayRoomBaseInfoIsEightyTwoBytes){EXPECT_EQ(sizeof(MnhPlayRoomBaseInfo),82u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,dwPlayRoomIndex),0u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,strPlayRoomTitle),4u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,cbPlayRoomKind),68u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,wMaxObserver),69u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,wMaxPlayerPerTeam),71u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,MoneyForPlay),73u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,wPlayerNum),77u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,cbStart),79u);EXPECT_EQ(offsetof(MnhPlayRoomBaseInfo,wMapNum),80u);}
TEST(MurimNetWire, MsgTeamChangeIsThirteenBytes){EXPECT_EQ(sizeof(MnhMsgTeamChange),13u);EXPECT_EQ(offsetof(MnhMsgTeamChange,dwMoverID),7u);EXPECT_EQ(offsetof(MnhMsgTeamChange,cbFromTeam),11u);EXPECT_EQ(offsetof(MnhMsgTeamChange,cbToTeam),12u);}
TEST(MurimNetWire, ChannelInfoListIsHeaderPlusTenThousandEntries){EXPECT_EQ(sizeof(MnhMsgChannelBaseInfoList),sizeof(MnhWireBase)+4u+sizeof(MnhChannelBaseInfo)*MNH_MAX_CHANNEL_IN_MURIMNET);EXPECT_EQ(offsetof(MnhMsgChannelBaseInfoList,dwTotalChannelNum),7u);EXPECT_EQ(offsetof(MnhMsgChannelBaseInfoList,ChannelInfo),11u);}
TEST(MurimNetWire, PlayRoomInfoListIsHeaderPlusTenThousandEntries){EXPECT_EQ(sizeof(MnhMsgPlayRoomBaseInfoList),sizeof(MnhWireBase)+4u+sizeof(MnhPlayRoomBaseInfo)*MNH_MAX_PLAYROOM_IN_MURIMNET);EXPECT_EQ(offsetof(MnhMsgPlayRoomBaseInfoList,dwTotalPlayRoomNum),7u);EXPECT_EQ(offsetof(MnhMsgPlayRoomBaseInfoList,PlayRoomInfo),11u);}
TEST(MurimNetWire, CategoryByteIsThirtyEight){EXPECT_EQ(MNH_CATEGORY_MURIMNET,38u);}

TEST(MurimNetWire, MsgChatIsHundredAndThirtyFiveBytes){EXPECT_EQ(sizeof(MnhMsgChat),135u);EXPECT_EQ(offsetof(MnhMsgChat,Msg),7u);}