// server_misc_constants_sweep_test.cpp - Phase 6.3 byte sweep across non-agent
// server-side modules + agent constants not yet covered by prior sweeps.

#include <gtest/gtest.h>

#include "mxh/proto/negotiate.hpp"
#include "mxh/server/agent_cheat.hpp"
#include "mxh/server/agent_gtournament_server.hpp"
#include "mxh/server/agent_powerup.hpp"
#include "mxh/server/agent_userconn.hpp"

TEST(Negotiate, KProtocolVersionCurrentIs1) { EXPECT_EQ(mxh::proto::kProtocolVersionCurrent, 1u); }
TEST(Negotiate, KProtocolVersionLegacyIs0) { EXPECT_EQ(mxh::proto::kProtocolVersionLegacy, 0u); }
TEST(Negotiate, KAckSuccessIs1) { EXPECT_EQ(mxh::proto::kAckSuccess, 1u); }
TEST(Negotiate, KAckFailIs255) { EXPECT_EQ(mxh::proto::kAckFail, 255u); }
TEST(Cheat, CheatCategoryIs11) { EXPECT_EQ(mxh::server::cheat_category, 11u); }
TEST(Cheat, CheatUserLevelGmIs1) { EXPECT_EQ(mxh::server::cheat_user_level_gm, 1u); }
TEST(Cheat, CheatUserLevelProgrammerIs2) { EXPECT_EQ(mxh::server::cheat_user_level_programmer, 2u); }
TEST(Cheat, CheatUserLevelDeveloperIs3) { EXPECT_EQ(mxh::server::cheat_user_level_developer, 3u); }
TEST(Cheat, CheatUserLevelMonitorIs4) { EXPECT_EQ(mxh::server::cheat_user_level_monitor, 4u); }
TEST(Cheat, CheatUserLevelSuperuserIs5) { EXPECT_EQ(mxh::server::cheat_user_level_superuser, 5u); }
TEST(Cheat, CheatGmLoginSynIs0) { EXPECT_EQ(mxh::server::cheat_gm_login_syn, 0u); }
TEST(Cheat, CheatChangemapSynIs1) { EXPECT_EQ(mxh::server::cheat_changemap_syn, 1u); }
TEST(Cheat, CheatChangemapNackIs2) { EXPECT_EQ(mxh::server::cheat_changemap_nack, 2u); }
TEST(Cheat, CheatChangemapAckIs3) { EXPECT_EQ(mxh::server::cheat_changemap_ack, 3u); }
TEST(Cheat, CheatBancharacterSynIs4) { EXPECT_EQ(mxh::server::cheat_bancharacter_syn, 4u); }
TEST(Cheat, CheatBancharacterNackIs5) { EXPECT_EQ(mxh::server::cheat_bancharacter_nack, 5u); }
TEST(Cheat, CheatBlockcharacterSynIs6) { EXPECT_EQ(mxh::server::cheat_blockcharacter_syn, 6u); }
TEST(Cheat, CheatWhereisSynIs7) { EXPECT_EQ(mxh::server::cheat_whereis_syn, 7u); }
TEST(Cheat, CheatEventMonsterRegenIs8) { EXPECT_EQ(mxh::server::cheat_event_monster_regen, 8u); }
TEST(Cheat, CheatEventMonsterDeleteIs9) { EXPECT_EQ(mxh::server::cheat_event_monster_delete, 9u); }
TEST(Cheat, CheatBanmapSynIs10) { EXPECT_EQ(mxh::server::cheat_banmap_syn, 10u); }
TEST(Cheat, CheatAgentcheckSynIs11) { EXPECT_EQ(mxh::server::cheat_agentcheck_syn, 11u); }
TEST(Cheat, CheatPkallowSynIs12) { EXPECT_EQ(mxh::server::cheat_pkallow_syn, 12u); }
TEST(Cheat, CheatNoticeSynIs13) { EXPECT_EQ(mxh::server::cheat_notice_syn, 13u); }
TEST(Cheat, CheatAbilityexpSynIs14) { EXPECT_EQ(mxh::server::cheat_abilityexp_syn, 14u); }
TEST(Cheat, CheatAddmugongSynIs15) { EXPECT_EQ(mxh::server::cheat_addmugong_syn, 15u); }
TEST(Cheat, CheatMugongsungSynIs16) { EXPECT_EQ(mxh::server::cheat_mugongsung_syn, 16u); }
TEST(Cheat, CheatItemSynIs17) { EXPECT_EQ(mxh::server::cheat_item_syn, 17u); }
TEST(Cheat, CheatItemOptionSynIs18) { EXPECT_EQ(mxh::server::cheat_item_option_syn, 18u); }
TEST(Cheat, CheatMoneySynIs19) { EXPECT_EQ(mxh::server::cheat_money_syn, 19u); }
TEST(Cheat, CheatEventSynIs20) { EXPECT_EQ(mxh::server::cheat_event_syn, 20u); }
TEST(Cheat, CheatEventnotifyOnIs21) { EXPECT_EQ(mxh::server::cheat_eventnotify_on, 21u); }
TEST(Cheat, CheatPlustimeOnIs22) { EXPECT_EQ(mxh::server::cheat_plustime_on, 22u); }
TEST(Cheat, CheatEventnotifyOffIs23) { EXPECT_EQ(mxh::server::cheat_eventnotify_off, 23u); }
TEST(Cheat, CheatPlustimeAlloffIs24) { EXPECT_EQ(mxh::server::cheat_plustime_alloff, 24u); }
TEST(Cheat, CheatChangeEventmapSynIs25) { EXPECT_EQ(mxh::server::cheat_change_eventmap_syn, 25u); }
TEST(Cheat, CheatEventStartSynIs26) { EXPECT_EQ(mxh::server::cheat_event_start_syn, 26u); }
TEST(Cheat, CheatEventReadySynIs27) { EXPECT_EQ(mxh::server::cheat_event_ready_syn, 27u); }
TEST(Cheat, CheatPetStaminaIs28) { EXPECT_EQ(mxh::server::cheat_pet_stamina, 28u); }
TEST(Cheat, CheatPetFriendshipSynIs29) { EXPECT_EQ(mxh::server::cheat_pet_friendship_syn, 29u); }
TEST(Cheat, CheatPetSelectedFriendshipSynIs30) { EXPECT_EQ(mxh::server::cheat_pet_selected_friendship_syn, 30u); }
TEST(Cheat, CheatGuildpointSynIs31) { EXPECT_EQ(mxh::server::cheat_guildpoint_syn, 31u); }
TEST(Cheat, CheatGuildhuntedMonstercountSynIs32) { EXPECT_EQ(mxh::server::cheat_guildhunted_monstercount_syn, 32u); }
TEST(Cheat, CheatMussangReadyIs33) { EXPECT_EQ(mxh::server::cheat_mussang_ready, 33u); }
TEST(Cheat, CheatJackpotGetprizeIs34) { EXPECT_EQ(mxh::server::cheat_jackpot_getprize, 34u); }
TEST(Cheat, CheatJackpotMoneypermonsterIs35) { EXPECT_EQ(mxh::server::cheat_jackpot_moneypermonster, 35u); }
TEST(Cheat, CheatJackpotOnoffIs36) { EXPECT_EQ(mxh::server::cheat_jackpot_onoff, 36u); }
TEST(Cheat, CheatJackpotProbabilityIs37) { EXPECT_EQ(mxh::server::cheat_jackpot_probability, 37u); }
TEST(Cheat, CheatJackpotControlIs38) { EXPECT_EQ(mxh::server::cheat_jackpot_control, 38u); }
TEST(Cheat, CheatBobusanginfoRequestSynIs39) { EXPECT_EQ(mxh::server::cheat_bobusanginfo_request_syn, 39u); }
TEST(Cheat, CheatBobusangLeaveSynIs40) { EXPECT_EQ(mxh::server::cheat_bobusang_leave_syn, 40u); }
TEST(Cheat, CheatBobusanginfoChangeSynIs41) { EXPECT_EQ(mxh::server::cheat_bobusanginfo_change_syn, 41u); }
TEST(Cheat, CheatItemlimitSynIs42) { EXPECT_EQ(mxh::server::cheat_itemlimit_syn, 42u); }
TEST(Cheat, CheatAutonoteSettingSynIs43) { EXPECT_EQ(mxh::server::cheat_autonote_setting_syn, 43u); }
TEST(Cheat, CheatBancharacterAckIs50) { EXPECT_EQ(mxh::server::cheat_bancharacter_ack, 50u); }
TEST(Cheat, CheatWhereisAckIs52) { EXPECT_EQ(mxh::server::cheat_whereis_ack, 52u); }
TEST(Cheat, CheatDamageSynIs44) { EXPECT_EQ(mxh::server::cheat_damage_syn, 44u); }
TEST(Cheat, CheatDamageAckIs45) { EXPECT_EQ(mxh::server::cheat_damage_ack, 45u); }
TEST(Cheat, CheatDamageNackIs46) { EXPECT_EQ(mxh::server::cheat_damage_nack, 46u); }
TEST(Cheat, CheatMapConditionIs47) { EXPECT_EQ(mxh::server::cheat_map_condition, 47u); }
TEST(Cheat, CheatAgentConditionIs48) { EXPECT_EQ(mxh::server::cheat_agent_condition, 48u); }
TEST(Cheat, CheatTitanFuelSpellMaxSynIs49) { EXPECT_EQ(mxh::server::cheat_titan_fuel_spell_max_syn, 49u); }
TEST(Gtournament_server, GtoournamentCategoryIs59) { EXPECT_EQ(mxh::server::gtoournament_category, 59u); }
TEST(Gtournament_server, GtournamentMovetobattlemapSynIs0) { EXPECT_EQ(mxh::server::gtournament_movetobattlemap_syn, 0u); }
TEST(Gtournament_server, GtournamentMovetobattlemapNackIs1) { EXPECT_EQ(mxh::server::gtournament_movetobattlemap_nack, 1u); }
TEST(Gtournament_server, GtournamentStandinginfoSynIs2) { EXPECT_EQ(mxh::server::gtournament_standinginfo_syn, 2u); }
TEST(Gtournament_server, GtournamentStandinginfoNackIs3) { EXPECT_EQ(mxh::server::gtournament_standinginfo_nack, 3u); }
TEST(Gtournament_server, GtournamentBattlejoinSynIs4) { EXPECT_EQ(mxh::server::gtournament_battlejoin_syn, 4u); }
TEST(Gtournament_server, GtournamentObserverjoinSynIs5) { EXPECT_EQ(mxh::server::gtournament_observerjoin_syn, 5u); }
TEST(Gtournament_server, GtournamentBattlejoinNackIs6) { EXPECT_EQ(mxh::server::gtournament_battlejoin_nack, 6u); }
TEST(Gtournament_server, GtournamentLeaveSynIs7) { EXPECT_EQ(mxh::server::gtournament_leave_syn, 7u); }
TEST(Gtournament_server, GtournamentCheatIs8) { EXPECT_EQ(mxh::server::gtournament_cheat, 8u); }
TEST(Gtournament_server, GtournamentEventStartIs9) { EXPECT_EQ(mxh::server::gtournament_event_start, 9u); }
TEST(Gtournament_server, GtournamentEventEndIs10) { EXPECT_EQ(mxh::server::gtournament_event_end, 10u); }
TEST(Gtournament_server, GtournamentStandinginfoRegistedIs11) { EXPECT_EQ(mxh::server::gtournament_standinginfo_registed, 11u); }
TEST(Gtournament_server, GtournamentReturntomapIs12) { EXPECT_EQ(mxh::server::gtournament_returntomap, 12u); }
TEST(Gtournament_server, GtournamentNotifyWinloseIs13) { EXPECT_EQ(mxh::server::gtournament_notify_winlose, 13u); }
TEST(Gtournament_server, GtournamentMapNumIs60) { EXPECT_EQ(mxh::server::gtournament_map_num, 60u); }
TEST(Gtournament_server, GtournamentUserLevelMaxForEventStartIs1) { EXPECT_EQ(mxh::server::gtournament_user_level_max_for_event_start, 1u); }
TEST(Gtournament_server, GtournamentErrorIs0) { EXPECT_EQ(mxh::server::gtournament_error, 0u); }
TEST(Powerup, PowerupCategoryIs2) { EXPECT_EQ(mxh::server::powerup_category, 2u); }
TEST(Powerup, PowerupBootingNotifyIs0) { EXPECT_EQ(mxh::server::powerup_booting_notify, 0u); }
TEST(Powerup, PowerupBootlistSynIs1) { EXPECT_EQ(mxh::server::powerup_bootlist_syn, 1u); }
TEST(Powerup, PowerupBootlistAckIs2) { EXPECT_EQ(mxh::server::powerup_bootlist_ack, 2u); }
TEST(Powerup, PowerupConnectSynIs3) { EXPECT_EQ(mxh::server::powerup_connect_syn, 3u); }
TEST(Powerup, PowerupConnectAckIs4) { EXPECT_EQ(mxh::server::powerup_connect_ack, 4u); }
TEST(Powerup, PowerupMaxAgentServersIs100) { EXPECT_EQ(mxh::server::powerup_max_agent_servers, 100u); }
TEST(Userconn, UserconnCategoryIs7) { EXPECT_EQ(mxh::server::userconn_category, 7u); }
TEST(Userconn, UserconnDistConnectsuccessIs0) { EXPECT_EQ(mxh::server::userconn_dist_connectsuccess, 0u); }
TEST(Userconn, UserconnLoginSynIs1) { EXPECT_EQ(mxh::server::userconn_login_syn, 1u); }
TEST(Userconn, UserconnLoginAckIs2) { EXPECT_EQ(mxh::server::userconn_login_ack, 2u); }
TEST(Userconn, UserconnLoginNackIs3) { EXPECT_EQ(mxh::server::userconn_login_nack, 3u); }
TEST(Userconn, UserconnNotifyUserloginSynIs4) { EXPECT_EQ(mxh::server::userconn_notify_userlogin_syn, 4u); }
TEST(Userconn, UserconnNotifyUserloginAckIs5) { EXPECT_EQ(mxh::server::userconn_notify_userlogin_ack, 5u); }
TEST(Userconn, UserconnNotifyUserloginNackIs6) { EXPECT_EQ(mxh::server::userconn_notify_userlogin_nack, 6u); }
TEST(Userconn, UserconnNotifyOverlappedloginIs7) { EXPECT_EQ(mxh::server::userconn_notify_overlappedlogin, 7u); }
TEST(Userconn, UserconnAgentConnectsuccessIs8) { EXPECT_EQ(mxh::server::userconn_agent_connectsuccess, 8u); }
TEST(Userconn, UserconnCharacterlistSynIs9) { EXPECT_EQ(mxh::server::userconn_characterlist_syn, 9u); }
TEST(Userconn, UserconnDirectcharacterlistSynIs10) { EXPECT_EQ(mxh::server::userconn_directcharacterlist_syn, 10u); }
TEST(Userconn, UserconnCharacterlistNackIs11) { EXPECT_EQ(mxh::server::userconn_characterlist_nack, 11u); }
TEST(Userconn, UserconnCharacterlistAckIs12) { EXPECT_EQ(mxh::server::userconn_characterlist_ack, 12u); }
TEST(Userconn, UserconnDisconnectSynIs13) { EXPECT_EQ(mxh::server::userconn_disconnect_syn, 13u); }
TEST(Userconn, UserconnDisconnectAckIs14) { EXPECT_EQ(mxh::server::userconn_disconnect_ack, 14u); }
TEST(Userconn, UserconnDisconnectNackIs15) { EXPECT_EQ(mxh::server::userconn_disconnect_nack, 15u); }
TEST(Userconn, UserconnCharacterselectSynIs16) { EXPECT_EQ(mxh::server::userconn_characterselect_syn, 16u); }
TEST(Userconn, UserconnCharacterselectAckIs17) { EXPECT_EQ(mxh::server::userconn_characterselect_ack, 17u); }
TEST(Userconn, UserconnCharacterselectNackIs18) { EXPECT_EQ(mxh::server::userconn_characterselect_nack, 18u); }
TEST(Userconn, UserconnCharacterNamecheckSynIs19) { EXPECT_EQ(mxh::server::userconn_character_namecheck_syn, 19u); }
TEST(Userconn, UserconnCharacterNamecheckAckIs20) { EXPECT_EQ(mxh::server::userconn_character_namecheck_ack, 20u); }
TEST(Userconn, UserconnCharacterNamecheckNackIs21) { EXPECT_EQ(mxh::server::userconn_character_namecheck_nack, 21u); }
TEST(Userconn, UserconnCharacterMakeSynIs22) { EXPECT_EQ(mxh::server::userconn_character_make_syn, 22u); }
TEST(Userconn, UserconnCharacterMakeAckIs23) { EXPECT_EQ(mxh::server::userconn_character_make_ack, 23u); }
TEST(Userconn, UserconnCharacterMakeNackIs24) { EXPECT_EQ(mxh::server::userconn_character_make_nack, 24u); }
TEST(Userconn, UserconnCharacterInfoSynIs25) { EXPECT_EQ(mxh::server::userconn_character_info_syn, 25u); }
TEST(Userconn, UserconnCharacterInfoAckIs26) { EXPECT_EQ(mxh::server::userconn_character_info_ack, 26u); }
TEST(Userconn, UserconnCharacterInfoNackIs27) { EXPECT_EQ(mxh::server::userconn_character_info_nack, 27u); }
TEST(Userconn, UserconnGameinSynIs28) { EXPECT_EQ(mxh::server::userconn_gamein_syn, 28u); }
TEST(Userconn, UserconnGameinAckIs29) { EXPECT_EQ(mxh::server::userconn_gamein_ack, 29u); }
TEST(Userconn, UserconnGameinNackIs30) { EXPECT_EQ(mxh::server::userconn_gamein_nack, 30u); }
TEST(Userconn, UserconnGameoutSynIs31) { EXPECT_EQ(mxh::server::userconn_gameout_syn, 31u); }
TEST(Userconn, UserconnGameoutAckIs32) { EXPECT_EQ(mxh::server::userconn_gameout_ack, 32u); }
TEST(Userconn, UserconnGameoutNackIs33) { EXPECT_EQ(mxh::server::userconn_gameout_nack, 33u); }
TEST(Userconn, UserconnDisconnectedIs34) { EXPECT_EQ(mxh::server::userconn_disconnected, 34u); }
TEST(Userconn, UserconnCharacterAddIs35) { EXPECT_EQ(mxh::server::userconn_character_add, 35u); }
TEST(Userconn, UserconnPetAddIs36) { EXPECT_EQ(mxh::server::userconn_pet_add, 36u); }
TEST(Userconn, UserconnMonsterAddIs37) { EXPECT_EQ(mxh::server::userconn_monster_add, 37u); }
TEST(Userconn, UserconnBossmonsterAddIs38) { EXPECT_EQ(mxh::server::userconn_bossmonster_add, 38u); }
TEST(Userconn, UserconnNpcAddIs39) { EXPECT_EQ(mxh::server::userconn_npc_add, 39u); }
TEST(Userconn, UserconnObjectRemoveIs40) { EXPECT_EQ(mxh::server::userconn_object_remove, 40u); }
TEST(Userconn, UserconnCharacterDieIs41) { EXPECT_EQ(mxh::server::userconn_character_die, 41u); }
TEST(Userconn, UserconnMonsterDieIs42) { EXPECT_EQ(mxh::server::userconn_monster_die, 42u); }
TEST(Userconn, UserconnPetDieIs43) { EXPECT_EQ(mxh::server::userconn_pet_die, 43u); }
TEST(Userconn, UserconnCharacterReviveIs44) { EXPECT_EQ(mxh::server::userconn_character_revive, 44u); }
TEST(Userconn, UserconnCharacterRemoveSynIs45) { EXPECT_EQ(mxh::server::userconn_character_remove_syn, 45u); }
TEST(Userconn, UserconnCharacterRemoveAckIs46) { EXPECT_EQ(mxh::server::userconn_character_remove_ack, 46u); }
TEST(Userconn, UserconnCharacterRemoveNackIs47) { EXPECT_EQ(mxh::server::userconn_character_remove_nack, 47u); }
TEST(Userconn, UserconnChangemapSynIs48) { EXPECT_EQ(mxh::server::userconn_changemap_syn, 48u); }
TEST(Userconn, UserconnChangemapAckIs49) { EXPECT_EQ(mxh::server::userconn_changemap_ack, 49u); }
TEST(Userconn, UserconnChangemapNackIs50) { EXPECT_EQ(mxh::server::userconn_changemap_nack, 50u); }
TEST(Userconn, UserconnMapOutIs51) { EXPECT_EQ(mxh::server::userconn_map_out, 51u); }
TEST(Userconn, UserconnMapOutWithmapnumIs52) { EXPECT_EQ(mxh::server::userconn_map_out_withmapnum, 52u); }
TEST(Userconn, UserconnCharacterTotalinfoIs53) { EXPECT_EQ(mxh::server::userconn_character_totalinfo, 53u); }
TEST(Userconn, UserconnSavepointSynIs54) { EXPECT_EQ(mxh::server::userconn_savepoint_syn, 54u); }
TEST(Userconn, UserconnSavepointAckIs55) { EXPECT_EQ(mxh::server::userconn_savepoint_ack, 55u); }
TEST(Userconn, UserconnSavepointNackIs56) { EXPECT_EQ(mxh::server::userconn_savepoint_nack, 56u); }
TEST(Userconn, UserconnBacktocharselSynIs57) { EXPECT_EQ(mxh::server::userconn_backtocharsel_syn, 57u); }
TEST(Userconn, UserconnBacktocharselAckIs58) { EXPECT_EQ(mxh::server::userconn_backtocharsel_ack, 58u); }
TEST(Userconn, UserconnBacktocharselNackIs59) { EXPECT_EQ(mxh::server::userconn_backtocharsel_nack, 59u); }
TEST(Userconn, UserconnGridinitIs60) { EXPECT_EQ(mxh::server::userconn_gridinit, 60u); }
TEST(Userconn, UserconnSetvisibleIs61) { EXPECT_EQ(mxh::server::userconn_setvisible, 61u); }
TEST(Userconn, UserconnOtheruserConnecttryNotifyIs62) { EXPECT_EQ(mxh::server::userconn_otheruser_connecttry_notify, 62u); }
TEST(Userconn, UserconnConnectionCheckIs63) { EXPECT_EQ(mxh::server::userconn_connection_check, 63u); }
TEST(Userconn, UserconnConnectionCheckOkIs64) { EXPECT_EQ(mxh::server::userconn_connection_check_ok, 64u); }
TEST(Userconn, UserconnChecksumerrorIs65) { EXPECT_EQ(mxh::server::userconn_checksumerror, 65u); }
TEST(Userconn, UserconnForceDisconnectOverlaploginIs66) { EXPECT_EQ(mxh::server::userconn_force_disconnect_overlaplogin, 66u); }
TEST(Userconn, UserconnDisconnectedByOverlaploginIs67) { EXPECT_EQ(mxh::server::userconn_disconnected_by_overlaplogin, 67u); }
TEST(Userconn, UserconnChannelinfoSynIs68) { EXPECT_EQ(mxh::server::userconn_channelinfo_syn, 68u); }
TEST(Userconn, UserconnChannelinfoAckIs69) { EXPECT_EQ(mxh::server::userconn_channelinfo_ack, 69u); }
TEST(Userconn, UserconnChannelinfoNackIs70) { EXPECT_EQ(mxh::server::userconn_channelinfo_nack, 70u); }
TEST(Userconn, UserconnNotifytoagentAlreadyoutIs71) { EXPECT_EQ(mxh::server::userconn_notifytoagent_alreadyout, 71u); }
TEST(Userconn, UserconnRequestDistoutIs72) { EXPECT_EQ(mxh::server::userconn_request_distout, 72u); }
TEST(Userconn, UserconnDisconnectedOnLoginIs73) { EXPECT_EQ(mxh::server::userconn_disconnected_on_login, 73u); }
TEST(Userconn, UserconnServerNotreadyIs74) { EXPECT_EQ(mxh::server::userconn_server_notready, 74u); }
TEST(Userconn, UserconnMapdescIs75) { EXPECT_EQ(mxh::server::userconn_mapdesc, 75u); }
TEST(Userconn, UserconnCharacterReviveNackIs76) { EXPECT_EQ(mxh::server::userconn_character_revive_nack, 76u); }
TEST(Userconn, UserconnReadyToReviveIs77) { EXPECT_EQ(mxh::server::userconn_ready_to_revive, 77u); }
TEST(Userconn, UserconnCheatUsingIs78) { EXPECT_EQ(mxh::server::userconn_cheat_using, 78u); }
TEST(Userconn, UserconnCheatChangemapAckIs79) { EXPECT_EQ(mxh::server::userconn_cheat_changemap_ack, 79u); }
TEST(Userconn, UserconnUseDynamicSynIs80) { EXPECT_EQ(mxh::server::userconn_use_dynamic_syn, 80u); }
TEST(Userconn, UserconnUseDynamicAckIs81) { EXPECT_EQ(mxh::server::userconn_use_dynamic_ack, 81u); }
TEST(Userconn, UserconnUseDynamicNackIs82) { EXPECT_EQ(mxh::server::userconn_use_dynamic_nack, 82u); }
TEST(Userconn, UserconnLoginDynamicSynIs83) { EXPECT_EQ(mxh::server::userconn_login_dynamic_syn, 83u); }
TEST(Userconn, UserconnLoginDynamicAckIs84) { EXPECT_EQ(mxh::server::userconn_login_dynamic_ack, 84u); }
TEST(Userconn, UserconnLoginDynamicNackIs85) { EXPECT_EQ(mxh::server::userconn_login_dynamic_nack, 85u); }
TEST(Userconn, UserconnLogincheckDeleteIs86) { EXPECT_EQ(mxh::server::userconn_logincheck_delete, 86u); }
TEST(Userconn, UserconnForceDisconnectOverlaploginAckIs87) { EXPECT_EQ(mxh::server::userconn_force_disconnect_overlaplogin_ack, 87u); }
TEST(Userconn, UserconnMapOutToEventmapIs88) { EXPECT_EQ(mxh::server::userconn_map_out_to_eventmap, 88u); }
TEST(Userconn, UserconnMapOutToEventbeforemapIs89) { EXPECT_EQ(mxh::server::userconn_map_out_to_eventbeforemap, 89u); }
TEST(Userconn, UserconnEnterEventmapSynIs90) { EXPECT_EQ(mxh::server::userconn_enter_eventmap_syn, 90u); }
TEST(Userconn, UserconnEventReadyIs91) { EXPECT_EQ(mxh::server::userconn_event_ready, 91u); }
TEST(Userconn, UserconnEventStartIs92) { EXPECT_EQ(mxh::server::userconn_event_start, 92u); }
TEST(Userconn, UserconnEventEndIs93) { EXPECT_EQ(mxh::server::userconn_event_end, 93u); }
TEST(Userconn, UserconnEventitemUseIs94) { EXPECT_EQ(mxh::server::userconn_eventitem_use, 94u); }
TEST(Userconn, UserconnEventitemUse2Is95) { EXPECT_EQ(mxh::server::userconn_eventitem_use2, 95u); }
TEST(Userconn, UserconnGameinposSynIs96) { EXPECT_EQ(mxh::server::userconn_gameinpos_syn, 96u); }
TEST(Userconn, UserconnGameinposAckIs97) { EXPECT_EQ(mxh::server::userconn_gameinpos_ack, 97u); }
TEST(Userconn, UserconnGameinposNackIs98) { EXPECT_EQ(mxh::server::userconn_gameinpos_nack, 98u); }
TEST(Userconn, UserconnRemaintimeNotifyIs99) { EXPECT_EQ(mxh::server::userconn_remaintime_notify, 99u); }
TEST(Userconn, UserconnBacktobeforemapTouserIs100) { EXPECT_EQ(mxh::server::userconn_backtobeforemap_touser, 100u); }
TEST(Userconn, UserconnBacktobeforemapSynIs101) { EXPECT_EQ(mxh::server::userconn_backtobeforemap_syn, 101u); }
TEST(Userconn, UserconnBacktobeforemapAckIs102) { EXPECT_EQ(mxh::server::userconn_backtobeforemap_ack, 102u); }
TEST(Userconn, UserconnBacktobeforemapNackIs103) { EXPECT_EQ(mxh::server::userconn_backtobeforemap_nack, 103u); }
TEST(Userconn, UserconnEnterGtournamentSynIs104) { EXPECT_EQ(mxh::server::userconn_enter_gtournament_syn, 104u); }
TEST(Userconn, UserconnCharacterslotIs105) { EXPECT_EQ(mxh::server::userconn_characterslot, 105u); }
TEST(Userconn, UserconnCastlegateAddIs106) { EXPECT_EQ(mxh::server::userconn_castlegate_add, 106u); }
TEST(Userconn, UserconnGameinOthermapSynIs107) { EXPECT_EQ(mxh::server::userconn_gamein_othermap_syn, 107u); }
TEST(Userconn, UserconnNowaitexitplayerIs108) { EXPECT_EQ(mxh::server::userconn_nowaitexitplayer, 108u); }
TEST(Userconn, UserconnFlagnpcOnoffIs109) { EXPECT_EQ(mxh::server::userconn_flagnpc_onoff, 109u); }
TEST(Userconn, UserconnLoginSynBuddyIs110) { EXPECT_EQ(mxh::server::userconn_login_syn_buddy, 110u); }
TEST(Userconn, UserconnChangemapChannelinfoSynIs111) { EXPECT_EQ(mxh::server::userconn_changemap_channelinfo_syn, 111u); }
TEST(Userconn, UserconnChangemapChannelinfoAckIs112) { EXPECT_EQ(mxh::server::userconn_changemap_channelinfo_ack, 112u); }
TEST(Userconn, UserconnChangemapChannelinfoNackIs113) { EXPECT_EQ(mxh::server::userconn_changemap_channelinfo_nack, 113u); }
TEST(Userconn, UserconnCurrentmapChannelinfoIs114) { EXPECT_EQ(mxh::server::userconn_currentmap_channelinfo, 114u); }
TEST(Userconn, UserconnLoginErrNoAgentServerIs0) { EXPECT_EQ(mxh::server::userconn_login_err_no_agent_server, 0u); }
TEST(Userconn, UserconnLoginErrDistAlreadyoutIs1) { EXPECT_EQ(mxh::server::userconn_login_err_dist_alreadyout, 1u); }
TEST(Userconn, UserconnLoginErrOverlapIs2) { EXPECT_EQ(mxh::server::userconn_login_err_overlap, 2u); }
TEST(Userconn, UserconnLoginErrNoUserIs3) { EXPECT_EQ(mxh::server::userconn_login_err_no_user, 3u); }
