# scripts/check-dup-headers.ps1
#
# 防止 R-36 / R-37 再发 (2026-08-20 ABI 错位事故根因).
#
# 背景: src/ui/ 跟 include/mxh/ui/ 都有 .hpp 真目录副本 (历史: include 是
# junction 改的真目录, 2026-08-18 commit ca6b0ee3 解锁). 两边 SHA256 必须
# 保持一致, 否则 .obj 用 src/ 老 layout 编译, test 用 include/ 新 layout
# 编译, build 通过但 ABI 错, 运行时 0xC0000005.
#
# 用法:
#   pwsh -File scripts\check-dup-headers.ps1           # 审计, 出错返 1
#   pwsh -File scripts\check-dup-headers.ps1 -Fix     # 同步 src/ → include/ (双向以 SHA256 多的为准)
#
# 也可装 git pre-commit hook:
#   pwsh -File scripts\check-dup-headers.ps1 -InstallHook

[CmdletBinding()]
param(
    [switch]$Fix,
    [switch]$InstallHook
)

$ErrorActionPreference = 'Stop'

# Resolve repo root as parent of scripts/ dir. Use string concat instead of
# Join-Path because PSPath in CJK paths sometimes splits incorrectly.
$scriptFull = (Resolve-Path -LiteralPath $PSScriptRoot).Path
$repoRoot   = Split-Path -Parent $scriptFull
$srcDir     = $repoRoot + '\modern\src\ui'
$incDir     = $repoRoot + '\modern\include\mxh\ui'
Write-Debug "scriptFull=$scriptFull"
Write-Debug "repoRoot=$repoRoot"
Write-Debug "srcDir=$srcDir"
Write-Debug "incDir=$incDir"

if (-not (Test-Path -LiteralPath $srcDir)) {
    Write-Error "src dir not found: $srcDir"
}
if (-not (Test-Path -LiteralPath $incDir)) {
    Write-Error "include dir not found: $incDir"
}

if ($InstallHook) {
    $hookDir   = $repoRoot + '\.git\hooks'
    $hookPath  = $hookDir   + '\pre-commit'
    $scriptAbs = (Resolve-Path -LiteralPath $PSCommandPath).Path
    $hookContent = @"
#!/usr/bin/env pwsh
# Auto-generated by scripts/check-dup-headers.ps1 -InstallHook
# Pre-commit gate: 防止 src/ui/ 跟 include/mxh/ui/ .hpp ABI 错位
# (R-36 / R-37, 2026-08-20)
`$ErrorActionPreference = 'Stop'
& '$scriptAbs' -ErrorAction Stop
exit `$LASTEXITCODE
"@
    New-Item -ItemType Directory -Force -Path $hookDir | Out-Null
    Set-Content -LiteralPath $hookPath -Value $hookContent -Encoding UTF8
    Write-Host "Installed pre-commit hook: $hookPath"
    exit 0
}

$srcHpp = Get-ChildItem -LiteralPath $srcDir -Filter '*.hpp' -ErrorAction SilentlyContinue
$incHpp = Get-ChildItem -LiteralPath $incDir -Filter '*.hpp' -ErrorAction SilentlyContinue

$outOfSync = @()
$onlyInSrc = @()
$onlyInInc = @()

foreach ($s in $srcHpp) {
    $i = $incHpp | Where-Object { $_.Name -eq $s.Name } | Select-Object -First 1
    if (-not $i) {
        $onlyInSrc += $s
        continue
    }
    $sHash = (Get-FileHash -LiteralPath $s.FullName -Algorithm SHA256).Hash
    $iHash = (Get-FileHash -LiteralPath $i.FullName -Algorithm SHA256).Hash
    if ($sHash -ne $iHash) {
        $outOfSync += [PSCustomObject]@{
            Name     = $s.Name
            SrcHash  = $sHash.Substring(0, 12)
            IncHash  = $iHash.Substring(0, 12)
            SrcSize  = $s.Length
            IncSize  = $i.Length
        }
    }
}
foreach ($i in $incHpp) {
    $s = $srcHpp | Where-Object { $_.Name -eq $i.Name } | Select-Object -First 1
    if (-not $s) { $onlyInInc += $i }
}

if ($onlyInSrc.Count -gt 0) {
    Write-Host "Files only in src/ui (NOT in include/mxh/ui/):"
    $onlyInSrc | ForEach-Object { Write-Host "  $($_.Name)" }
}
if ($onlyInInc.Count -gt 0) {
    # Files only in include/mxh/ui/ are common — those are new modern-only
    # headers (e.g. cAni.hpp / cItemShopInven.hpp stubs, resolution_mode.hpp).
    # They're not ABI risk because they only have one location; just FYI.
    Write-Host "Files only in include/mxh/ui/ (NOT in src/ui) [FYI, no .cpp uses them]:"
    $onlyInInc | ForEach-Object { Write-Host "  $($_.Name)" }
}

if ($outOfSync.Count -eq 0 -and $onlyInSrc.Count -eq 0) {
    Write-Host "OK: all duplicate .hpp files in sync (src/ui/ ↔ include/mxh/ui/)"
    exit 0
}

if ($outOfSync.Count -gt 0) {
    Write-Host ""
    Write-Host "OUT-OF-SYNC (R-36/R-37 risk):"
    $outOfSync | Format-Table -AutoSize | Out-String | Write-Host
}

if ($Fix) {
    Write-Host "-Fix: copying src/ui/*.hpp → include/mxh/ui/ (overwrite)"
    foreach ($o in $outOfSync) {
        $srcPath = $srcDir + '\' + $o.Name
        $incPath = $incDir + '\' + $o.Name
        Copy-Item -LiteralPath $srcPath -Destination $incPath -Force
        Write-Host "  fixed: $($o.Name)"
    }
    Write-Host "Re-running audit..."
    & $PSCommandPath
    exit $LASTEXITCODE
}

Write-Host "FAIL: $outOfSync.Count out-of-sync + $onlyInSrc.Count missing in include."
Write-Host "      Run with -Fix to sync src/ui/ → include/mxh/ui/."
exit 1
