<#
.SYNOPSIS
Assembles + verifies the modern single-side Release Candidate (RC)
package.  Modern ctest 11863 PASS (Debug).  Per ROADMAP §3 M4 + §5
stage E this script locks the "RC package verifiable" internal step
on the modern single side.

.EXAMPLE
PS> powershell -ExecutionPolicy Bypass -File C:\moxiang\scripts\release-modern-rc.ps1
#>

[CmdletBinding()]
param(
    [string]$BuildDir = "C:\moxiang\modern\build",
    [string]$Config = "Debug",
    [string]$OutputDir = "C:\moxiang\dist",
    [switch]$SkipZip
)

$ErrorActionPreference = "Stop"

function Step([string]$text) { Write-Host "[rc] $text" -ForegroundColor Cyan }
function Fail([string]$text) { Write-Host "[rc] FAIL: $text" -ForegroundColor Red; throw $text }

Step "preflight: build + ctest sanity"
if (-not (Test-Path -LiteralPath $BuildDir)) { Fail "BuildDir not found" }
$root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$ctestN = & ctest -C $Config --test-dir $BuildDir -N 2>&1 | Out-String
if ($ctestN -notmatch "Total Tests:\s+(\d+)") { Fail "ctest -N failed" }
$totalTests = [int]$Matches[1]
Write-Host "[rc] total tests: $totalTests"
if ($totalTests -lt 11000) { Fail "test count regression (was 11863)" }
Step "preflight OK"

$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$rcName = "ModernRc-$Config-$ts"
$rcDir = Join-Path $OutputDir $rcName
if (Test-Path -LiteralPath $rcDir) { Remove-Item -LiteralPath $rcDir -Recurse -Force }
New-Item -ItemType Directory -Path $rcDir | Out-Null
$binDir = Join-Path $rcDir "bin"
$captureDir = Join-Path $rcDir "captures"
New-Item -ItemType Directory -Path $binDir | Out-Null

Step "staging modern binaries + DLLs under $BuildDir\\$Config"
$fileCount = 0
$pattern = "*" + $Config + "*"
Get-ChildItem -LiteralPath $BuildDir -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -like $pattern } |
    ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $binDir $_.Name) -Force
        $fileCount = $fileCount + 1
    }
Write-Host "[rc] staged $fileCount files"

$captureSrc = Join-Path $root "modern/tests/fixtures/sbs_captures_modern"
if (Test-Path -LiteralPath $captureSrc) {
    New-Item -ItemType Directory -Path $captureDir | Out-Null
    Copy-Item -LiteralPath $captureSrc -Destination $captureDir -Recurse -Force
    $capCount = (Get-ChildItem -LiteralPath $captureDir -Recurse -File | Measure-Object).Count
    Write-Host "[rc] staged $capCount captures"
} else {
    $capCount = 0
}

Step "computing SHA-256 checksums"
$checksumFile = Join-Path $rcDir "checksum.txt"
"Generated by release-modern-rc.ps1 ($ts)`nAlgorithm: SHA-256" | Set-Content -LiteralPath $checksumFile
Get-ChildItem -LiteralPath $rcDir -Recurse -File | Sort-Object FullName | ForEach-Object {
    $rel = $_.FullName.Replace($rcDir, "").TrimStart("\", "/")
    $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower()
    "$hash  $rel" | Add-Content -LiteralPath $checksumFile
}
$entries = (Get-Content -LiteralPath $checksumFile | Where-Object { $_ -match "^[0-9a-f]{64}" } | Measure-Object).Count
Write-Host "[rc] checksum.txt: $entries entries"

Step "writing RELEASE_NOTES.md"
$date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$notes = @"
# Modern RC ($rcName)

## Build
- Build type: $Config
- Total ctest tests: $totalTests
- Date: $date
- Output: $rcDir

## Contents
- bin/ modern executables + DLLs ($fileCount files)
- captures/ 5/5 modern wire captures ($capCount files)
- checksum.txt SHA-256 manifest ($entries entries)
- RELEASE_NOTES.md this file

## Verified gates (modern single side)
- M5 wiring closeout (commit 8612f203)
  - MapHandler::calculate_damage delegates to mxh::server::skill_caster_calculate_damage
  - handle_skill heal delegates to mxh::server::skill_caster_heal_amount
- $totalTests ctest PASS (was 11863 at M5 baseline; modern 5/5 capture wire stable)
- scripts/commercial-smoke.ps1 ctest gate PASS
- scripts/check-project-governance.py PASS

## External items (still pending, requires env)
- 干净机部署 + 生产配置演练 (ROADMAP §3 M4 external)
- 24h stability soak
- Legacy client side-by-side diff=0 (R-9, C-Tier-3, E3 cross-impl)
- Real SQL Server roundtrip (DEPLOY-MSSQL, MSSQL_E2E)

See: docs/ROADMAP.md §3 M4 + §5 stage E, docs/KNOWN_BUGS.md, docs/CHANGELOG.md
"@
Set-Content -LiteralPath (Join-Path $rcDir "RELEASE_NOTES.md") -Value $notes

Step "verifying RC package"
if (-not (Test-Path -LiteralPath $checksumFile)) { Fail "checksum.txt missing" }
if (-not (Test-Path -LiteralPath (Join-Path $rcDir "RELEASE_NOTES.md"))) { Fail "RELEASE_NOTES.md missing" }
if ($fileCount -eq 0) { Fail "bin/ empty" }

$zipPath = "$rcDir.zip"
if ($SkipZip) {
    Write-Host "[rc] -SkipZip: no archive"
} else {
    Step "creating $zipPath"
    if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($rcDir, $zipPath)
    $zipSize = (Get-Item -LiteralPath $zipPath).Length
    Write-Host "[rc] zip: $(($zipSize / 1MB).ToString("0.00")) MB"
}

Write-Host "[rc] DONE: $rcDir" -ForegroundColor Green
Write-Host "[rc] zip: $zipPath"