// MhFileEx.cpp - Implementation of .bin format reader/writer.
//
// Original source: 墨香【源码】\[Tool]PackingMan\MHFileEx.cpp
// Algorithm reproduced verbatim from the original code's CMHFileEx::OpenBin().
//
// IMPORTANT real-file layout (from OpenBin()):
//   [12 bytes MHFILE_HEADER]
//   [1 byte CRC1]                                  <- always present
//   [_RXMSO_ defined: +1 byte extra CRC]
//   [_MSO50_ defined: +3 bytes extra CRC]
//   [dwDataSize bytes encrypted payload]
//   [_RXMSO_ defined: +1 byte extra CRC]
//   [_MSO50_ defined: +2 bytes extra CRC]
//   [1 byte CRC2]                                  <- always present
//
// CheckHeader() is COMMENTED OUT in the original (returns TRUE early),
// so dwVersion is NOT validated. Only dwDataSize is trusted.
// We replicate that behavior to stay 1:1 compatible.
//
// LEGACY 2008 PACKINGMAN FORMAT (R-17, seen in 107 server .bin files):
//   Layout: [uint32 file_size (= total file size)] [payload bytes]
//   Payload uses positional XOR (type=0) only. No version/type fields.
//   Detection: first uint32 equals total file size AND file has at least 5 bytes.
//   Modern format never satisfies this (modern +0 is a date+type+size hash
//   like 20040308+type+size, which never equals the file size for non-trivial
//   payloads). See modern/tests/unit/compat/resource_parse_all_bin_test.cpp
//   and KNOWN_BUGS.md R-17 for the 107 FAIL -> PASS fix.

#include "mxh/compat/mh_file_ex.hpp"

#include <algorithm>
#include <cstring>
#include <fstream>
#include <iostream>

namespace mxh::compat {

namespace {

// Note: original CMHFileEx::CheckHeader() is COMMENTED OUT, so dwVersion
// is never validated at runtime. We replicate that behavior. The "valid"
// version constants are documented for reference only.

}  // namespace

bool is_mh_bin(std::span<const std::uint8_t> bytes) noexcept {
    if (bytes.size() < sizeof(MhFileHeader)) return false;
    MhFileHeader h{};
    std::memcpy(&h, bytes.data(), sizeof(h));
    // Real-world: dwVersion is generated by the tool as 20040308+type+size
    // (or 20070522+...); CheckHeader is disabled, so we don't validate it.
    // We only sanity-check dwDataSize. dwType can be any positive integer.
    return h.file_size > 0 && h.file_size <= (1u << 28);  // 256 MB cap
}

bool is_size_prefixed_opaque_server_profile(
    std::span<const std::uint8_t> bytes) noexcept {
    if (bytes.size() < 5 || bytes.size() > 256u * 1024u * 1024u) {
        return false;
    }
    std::uint32_t total_size = 0;
    std::memcpy(&total_size, bytes.data(), sizeof(total_size));
    // The marker is structural, not a decoder claim: callers still need a
    // profile manifest to establish that this is a Server resource.
    return total_size == bytes.size();
}

std::uint8_t compute_crc8(std::span<const std::uint8_t> bytes) noexcept {
    std::uint8_t sum = 0;
    for (auto b : bytes) {
        sum = static_cast<std::uint8_t>(sum + b);
    }
    return sum;
}

std::vector<std::uint8_t> decrypt_bin_payload(
    std::span<const std::uint8_t> encrypted,
    std::uint32_t type) noexcept {
    // EXACT algorithm from MHFileEx.cpp:
    //
    //   for (DWORD i = 0; i < dwSize; ++i)
    //   {
    //       m_pData[i] -= (char)i;
    //       if (m_bRead == TRUE)
    //       {
    //           if (i % m_DOFtype == 0)
    //               m_pData[i] -= m_DOFtype;
    //       }
    //   }
    //
    // type=0: simple positional XOR (-= i)
    // type>0: additionally subtract type at every position where (i % type == 0)
    std::vector<std::uint8_t> out(encrypted.begin(), encrypted.end());
    const auto size = static_cast<std::uint32_t>(out.size());
    for (std::uint32_t i = 0; i < size; ++i) {
        const auto orig = static_cast<std::int32_t>(out[i]);
        std::int32_t v = orig - static_cast<std::int32_t>(i);
        if (type != 0 && (i % type) == 0) {
            v -= static_cast<std::int32_t>(type);
        }
        out[i] = static_cast<std::uint8_t>(v);
    }
    return out;
}

std::vector<std::uint8_t> encrypt_bin_payload(
    std::span<const std::uint8_t> raw,
    std::uint32_t type) noexcept {
    // Inverse of decrypt: add instead of subtract.
    std::vector<std::uint8_t> out(raw.begin(), raw.end());
    const auto size = static_cast<std::uint32_t>(out.size());
    for (std::uint32_t i = 0; i < size; ++i) {
        const auto orig = static_cast<std::int32_t>(out[i]);
        std::int32_t v = orig + static_cast<std::int32_t>(i);
        if (type != 0 && (i % type) == 0) {
            v += static_cast<std::int32_t>(type);
        }
        out[i] = static_cast<std::uint8_t>(v);
    }
    return out;
}

Result<MhFile> read_mh_bin(const std::filesystem::path& path) {
    Result<MhFile> r;
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) {
        r.error = MhError::FileNotFound;
        return r;
    }
    const auto total_size = static_cast<std::size_t>(f.tellg());
    f.seekg(0);
    std::vector<std::uint8_t> buf(total_size);
    if (!f.read(reinterpret_cast<char*>(buf.data()), total_size)) {
        r.error = MhError::IoError;
        return r;
    }

    // Legacy 2008 size-prefixed resources use positional decoding.  The same
    // structural marker is also used by the newer opaque server profile; the
    // caller must select the profile explicitly before treating the result as
    // gameplay data.  Keep this compatibility behavior for existing fixtures.
    //   layout: [uint32 file_size][payload bytes]
    //   payload decryption: positional XOR (type=0) only.
    //   file_size = total_size - 4, type = 0.
    //   Modern format +0 is a hash like 20040308+type+size, never equals fs.
    if (buf.size() >= 5) {
        std::uint32_t legacy_size = 0;
        std::memcpy(&legacy_size, buf.data(), sizeof(legacy_size));
        if (legacy_size == static_cast<std::uint32_t>(buf.size())) {
            MhFile file;
            file.header.version = 0x00000001;
            file.header.type = 0;
            file.header.file_size = static_cast<std::uint32_t>(buf.size() - 4);
            const std::uint8_t* payload = buf.data() + 4;
            file.data = decrypt_bin_payload(
                {payload, file.header.file_size}, file.header.type);
            r.value = std::move(file);
            return r;
        }
    }

    // Minimum size: header(12) + crc1(1) + payload(0) + crc2(1) = 14 bytes.
    if (buf.size() < 14) {
        r.error = MhError::InvalidHeader;
        return r;
    }

    MhFile file;
    std::memcpy(&file.header, buf.data(), sizeof(MhFileHeader));

    // Real-world: dwVersion is NOT validated (CheckHeader is commented out in
    // original code). We only sanity-check dwDataSize.
    constexpr std::uint32_t kMaxFileSize = 256u * 1024u * 1024u;  // 256 MB cap
    if (file.header.file_size > kMaxFileSize) {
        r.error = MhError::InvalidHeader;
        return r;
    }
    if (file.header.type == 0) {
        // Original CheckHeader rejects type==0, but in practice real files
        // sometimes have type==0. Treat as "no extra XOR step".
        file.header.type = 0;
    }

    // Real layout: header(12) + crc1(1) + data(N) + crc2(1) = N + 14 bytes.
    constexpr std::size_t kOverhead = sizeof(MhFileHeader) + 1 + 1;
    if (buf.size() < kOverhead + file.header.file_size) {
        // Fallback: maybe header without CRCs (data starts at offset 12).
        if (buf.size() >= sizeof(MhFileHeader) + file.header.file_size) {
            const std::uint8_t* payload = buf.data() + sizeof(MhFileHeader);
            file.data = decrypt_bin_payload(
                {payload, file.header.file_size}, file.header.type);
            r.value = std::move(file);
            return r;
        }
        r.error = MhError::InvalidHeader;
        return r;
    }

    const std::uint8_t* payload = buf.data() + sizeof(MhFileHeader) + 1;
    file.data = decrypt_bin_payload(
        {payload, file.header.file_size}, file.header.type);

    r.value = std::move(file);
    return r;
}

Result<MhFile> read_server_mh_bin(
    const std::filesystem::path& path, std::string_view profile_id) {
    if (profile_id == "playdh-current") {
        std::ifstream f(path, std::ios::binary | std::ios::ate);
        if (!f) return Result<MhFile>{{}, MhError::FileNotFound};
        const auto size = static_cast<std::size_t>(f.tellg());
        if (size < 5) return read_mh_bin(path);
        std::vector<std::uint8_t> bytes(size);
        f.seekg(0);
        if (!f.read(reinterpret_cast<char*>(bytes.data()),
                   static_cast<std::streamsize>(bytes.size()))) {
            return Result<MhFile>{{}, MhError::IoError};
        }
        if (is_size_prefixed_opaque_server_profile(bytes)) {
            return Result<MhFile>{{}, MhError::UnsupportedOpaqueServerProfile};
        }
        return read_mh_bin(path);
    }
    if (profile_id == "sworking-2008-reference") return read_mh_bin(path);
    return Result<MhFile>{{}, MhError::UnsupportedVersion};
}

Result<OpaqueServerContainer> read_opaque_server_container(
    const std::filesystem::path& path) {
    Result<OpaqueServerContainer> result;
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) {
        result.error = MhError::FileNotFound;
        return result;
    }
    const auto size = static_cast<std::size_t>(f.tellg());
    if (size < 5 || size > 256u * 1024u * 1024u) {
        result.error = MhError::UnsupportedOpaqueServerProfile;
        return result;
    }
    std::vector<std::uint8_t> bytes(size);
    f.seekg(0);
    if (!f.read(reinterpret_cast<char*>(bytes.data()),
                static_cast<std::streamsize>(bytes.size()))) {
        result.error = MhError::IoError;
        return result;
    }
    if (!is_size_prefixed_opaque_server_profile(bytes)) {
        result.error = MhError::UnsupportedOpaqueServerProfile;
        return result;
    }
    OpaqueServerContainer container;
    std::memcpy(&container.total_size, bytes.data(), sizeof(container.total_size));
    container.payload.assign(bytes.begin() + sizeof(container.total_size), bytes.end());
    result.value = std::move(container);
    return result;
}

MhError write_mh_bin(const std::filesystem::path& path,
                     std::span<const std::uint8_t> data,
                     std::uint32_t type) {
    MhFileHeader header{};
    header.version = 0x00000001;
    header.type = type;
    header.file_size = static_cast<std::uint32_t>(data.size());

    const auto encrypted = encrypt_bin_payload(data, type);

    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    if (!f) return MhError::PermissionDenied;

    f.write(reinterpret_cast<const char*>(&header), sizeof(header));
    f.write(reinterpret_cast<const char*>(encrypted.data()),
            static_cast<std::streamsize>(encrypted.size()));

    if (!f) return MhError::IoError;
    return MhError::Ok;
}

}  // namespace mxh::compat
