// MhFileEx.cpp - Implementation of .bin format reader/writer.
//
// Original source: 墨香【源码】\[Tool]PackingMan\MHFileEx.cpp
// Algorithm reproduced verbatim from the original code's CMHFileEx::OpenBin().
//
// IMPORTANT real-file layout (from OpenBin()):
//   [12 bytes MHFILE_HEADER]
//   [1 byte CRC1]                                  <- always present
//   [_RXMSO_ defined: +1 byte extra CRC]
//   [_MSO50_ defined: +3 bytes extra CRC]
//   [dwDataSize bytes encrypted payload]
//   [_RXMSO_ defined: +1 byte extra CRC]
//   [_MSO50_ defined: +2 bytes extra CRC]
//   [1 byte CRC2]                                  <- always present
//
// CheckHeader() is COMMENTED OUT in the original (returns TRUE early),
// so dwVersion is NOT validated. Only dwDataSize is trusted.
// We replicate that behavior to stay 1:1 compatible.

#include "mxh/compat/mh_file_ex.hpp"

#include <algorithm>
#include <cstring>
#include <fstream>
#include <iostream>

namespace mxh::compat {

namespace {

// Note: original CMHFileEx::CheckHeader() is COMMENTED OUT, so dwVersion
// is never validated at runtime. We replicate that behavior. The "valid"
// version constants are documented for reference only.

}  // namespace

bool is_mh_bin(std::span<const std::uint8_t> bytes) noexcept {
    if (bytes.size() < sizeof(MhFileHeader)) return false;
    MhFileHeader h{};
    std::memcpy(&h, bytes.data(), sizeof(h));
    // Real-world: dwVersion is generated by the tool as 20040308+type+size
    // (or 20070522+...); CheckHeader is disabled, so we don't validate it.
    // We only sanity-check dwDataSize. dwType can be any positive integer.
    return h.file_size > 0 && h.file_size <= (1u << 28);  // 256 MB cap
}

std::uint8_t compute_crc8(std::span<const std::uint8_t> bytes) noexcept {
    std::uint8_t sum = 0;
    for (auto b : bytes) {
        sum = static_cast<std::uint8_t>(sum + b);
    }
    return sum;
}

std::vector<std::uint8_t> decrypt_bin_payload(
    std::span<const std::uint8_t> encrypted,
    std::uint32_t type) noexcept {
    // EXACT algorithm from MHFileEx.cpp:
    //
    //   for (DWORD i = 0; i < dwSize; ++i)
    //   {
    //       m_pData[i] -= (char)i;
    //       if (m_bRead == TRUE)
    //       {
    //           if (i % m_DOFtype == 0)
    //               m_pData[i] -= m_DOFtype;
    //       }
    //   }
    //
    // type=0: simple positional XOR (-= i)
    // type>0: additionally subtract type at every position where (i % type == 0)
    std::vector<std::uint8_t> out(encrypted.begin(), encrypted.end());
    const auto size = static_cast<std::uint32_t>(out.size());
    for (std::uint32_t i = 0; i < size; ++i) {
        const auto orig = static_cast<std::int32_t>(out[i]);
        std::int32_t v = orig - static_cast<std::int32_t>(i);
        if (type != 0 && (i % type) == 0) {
            v -= static_cast<std::int32_t>(type);
        }
        out[i] = static_cast<std::uint8_t>(v);
    }
    return out;
}

std::vector<std::uint8_t> encrypt_bin_payload(
    std::span<const std::uint8_t> raw,
    std::uint32_t type) noexcept {
    // Inverse of decrypt: add instead of subtract.
    std::vector<std::uint8_t> out(raw.begin(), raw.end());
    const auto size = static_cast<std::uint32_t>(out.size());
    for (std::uint32_t i = 0; i < size; ++i) {
        const auto orig = static_cast<std::int32_t>(out[i]);
        std::int32_t v = orig + static_cast<std::int32_t>(i);
        if (type != 0 && (i % type) == 0) {
            v += static_cast<std::int32_t>(type);
        }
        out[i] = static_cast<std::uint8_t>(v);
    }
    return out;
}

Result<MhFile> read_mh_bin(const std::filesystem::path& path) {
    Result<MhFile> r;
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) {
        r.error = MhError::FileNotFound;
        return r;
    }
    const auto total_size = static_cast<std::size_t>(f.tellg());
    f.seekg(0);
    std::vector<std::uint8_t> buf(total_size);
    if (!f.read(reinterpret_cast<char*>(buf.data()), total_size)) {
        r.error = MhError::IoError;
        return r;
    }

    // Minimum size: header(12) + crc1(1) + payload(0) + crc2(1) = 14 bytes.
    if (buf.size() < 14) {
        r.error = MhError::InvalidHeader;
        return r;
    }

    MhFile file;
    std::memcpy(&file.header, buf.data(), sizeof(MhFileHeader));

    // Real-world: dwVersion is NOT validated (CheckHeader is commented out in
    // original code). We only sanity-check dwDataSize.
    constexpr std::uint32_t kMaxFileSize = 256u * 1024u * 1024u;  // 256 MB cap
    if (file.header.file_size == 0 || file.header.file_size > kMaxFileSize) {
        r.error = MhError::InvalidHeader;
        return r;
    }
    if (file.header.type == 0) {
        // Original CheckHeader rejects type==0, but in practice real files
        // sometimes have type==0. Treat as "no extra XOR step".
        file.header.type = 0;
    }

    // Real layout: header(12) + crc1(1) + data(N) + crc2(1) = N + 14 bytes.
    constexpr std::size_t kOverhead = sizeof(MhFileHeader) + 1 + 1;
    if (buf.size() < kOverhead + file.header.file_size) {
        // Fallback: maybe header without CRCs (data starts at offset 12).
        if (buf.size() >= sizeof(MhFileHeader) + file.header.file_size) {
            const std::uint8_t* payload = buf.data() + sizeof(MhFileHeader);
            file.data = decrypt_bin_payload(
                {payload, file.header.file_size}, file.header.type);
            r.value = std::move(file);
            return r;
        }
        r.error = MhError::InvalidHeader;
        return r;
    }

    const std::uint8_t* payload = buf.data() + sizeof(MhFileHeader) + 1;
    file.data = decrypt_bin_payload(
        {payload, file.header.file_size}, file.header.type);

    r.value = std::move(file);
    return r;
}

MhError write_mh_bin(const std::filesystem::path& path,
                     std::span<const std::uint8_t> data,
                     std::uint32_t type) {
    MhFileHeader header{};
    header.version = 0x00000001;
    header.type = type;
    header.file_size = static_cast<std::uint32_t>(data.size());

    const auto encrypted = encrypt_bin_payload(data, type);

    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    if (!f) return MhError::PermissionDenied;

    f.write(reinterpret_cast<const char*>(&header), sizeof(header));
    f.write(reinterpret_cast<const char*>(encrypted.data()),
            static_cast<std::streamsize>(encrypted.size()));

    if (!f) return MhError::IoError;
    return MhError::Ok;
}

}  // namespace mxh::compat